apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/pihole

patches:
  - target:
      kind: HTTPRoute
      name: pihole
      namespace: pihole
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: pihole.local.abbottland.io
  - target:
      kind: HTTPRoute
      name: pihole-http-to-https
      namespace: pihole
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: pihole.local.abbottland.io
