kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: regcred
  namespace: flux-system
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  template:
    metadata:
      name: regcred
      namespace: flux-system
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
    type: kubernetes.io/dockerconfigjson
  encryptedData:
    .dockerconfigjson: AgCAQwG+WcsPPIByWe3UgudwmJLOmOgSbvCOzQAQQm/Ol+NgsfcG+QZ4Q8tVOTfEtsHQa0pbjE1coMfo4Vs2RF0OG7NBjTkDBPxiRQfDXxW7h90U1kChJBvQ3Q4rVtvxAImqYlOCoHCMHQW7umyJNWShEb322uYBCuPiYqbm5L68oT3ECchvlBYJLhwrlxeAGNPJ0GQA4BgyHYTIN+Q8yYC8LIAA+Xo0yra/GJhGK+GeWinsmj3ebcvIXeTsTarp+nPDz/mdUfpI6oECWGtYnE11vefAB7S0m8MTmJqON1FVOyJ0nXus3e1bmvDBU5hi0rUKfzp5DESjmLHwchFgkqERE3IWIXRfRgUmYjjfN5nt2i1jDMhqqkY4SwpNoSYAVqi0SW66DD9e0c1DS3TSN57u5D26BA5veN4BQkhBDnz1xcpe2ul9TrtOSr7IFvP2yWv1hvXQ0y01obcRZgOluDtUDY0AtVxNoEiT+nn9H7LXYejSSpWSdS/Xxfzve6Dg69pxzlIzzZWCQQINpAhwqLH53y/PkcWbC0BgS9EmAUgL6cPSVRfxzSmbO9x3Xhdn/lun9PldGJBPWgCWmoqSagNtdvbfqPGqj0PtfiNZRexrXBE7kqw5MvXFUi21f4Jz43J/srtoj2TCHMhyxRKgHd1Ng3a5bquNn2FEpxCrn5ei1llVU92cU/1VU/chvxATYftoLqlcj+QlnFQUkfoGVwYwA4UrTNf/FKnJRwNmOeKNwiROihj/vwP6Qpc0riMM3t8eRf/MoypDKY62925nTKYNk52voIhFIHfvV77Wx638O11PTLc0O+ecMwDQn64o6YYMKFyj1SrDoqFIGwsQkx4HAHRG9zqEGv5QX2eglunb8NDKKcfbAYYurj/FwP7XeI+I1xep8p0J479jhb4L2Or9dkiJui+Gs6XPrllYyHqZfA==
