kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: regcred
  namespace: flux-system
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  template:
    metadata:
      name: regcred
      namespace: flux-system
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
    type: kubernetes.io/dockerconfigjson
  encryptedData:
    .dockerconfigjson: AgBgCFOMM/LVXkfewZL6r1fa9MqLJvp/w0DOf9ut4Xw/tgavksU2iUkCNpISr+ZCiQzMPMhtvPGaK6y68Bxsnv1V40/1UeTm/Whvh0Xcvh/Js0/QJY3f9zzCmWeTv72mnldG23SsYebZKEg7qDJQ3GNUBHK3NtawIx06Nmr05FIFM5ekwijPNAIZ5axOGGTezThsMC5HHsLkyRX3tL3bNwDopXzLMSLyeA6yqa84uxsWN1U2wIq5UVCjNau4eV3W7m8iBgoTSma1Wu1lHUX/scr7vVTvEyHLSG/8ObILrjDkqvw/1jH2gewkXzW8ykmGF+mfohnknygPoSw6VB+0pA1d/ondtAXvMA8XAK6y4Xe5+sFs9bi+akwJGBWGqYZA7b2qrQ0AGP7pUyNJzrUjq3nsZoW6/lB76IUtNpO0/035vIGeppK2yTuHeZqMeIFNWCdC3D9yFDI3kHrXIiUIEV/0Hrg1UgW84HVSBD5hXhT7Vdhuoe8LoC+VX3yzFtAe5160B51WN8zdboCWKU36/GXxZAldkw1cENVCf911qnOOjpaE2pCCO/wNYzhzu8USRQQrb8GVMjaGrMDKCMqlxArxlY2ZNcFlOmkJv/1zzau1zk4MuQHN53Pn6pz516eX6vkWzaehbG8QOGUIMbB/CxHJco3556HsxGh7IupYZvS/De4CcTMPT6YnkNClzUMz3GiQ3amgkMgjX8Am4t3hD7aAZffZVqD3LjVHb8o0KVksBqE6SskJ5jZo4OzCSh4PpIS1//KarHXC3y/V57sgvop8VEl87G6nHcX+tpqKA1VYZK/xc2g6oW0FtmYSYL/Ng0MogyBDb4GwGMRvbJfzDLCH5eqtlM6LgZSbj+4pkb9I4Sz3TqPOSJGdP+NZqnBwVKq9rZFrjf2NQEFEpAb9wrI09p8Gr23Az5MLkSAEQEJ3wA==
