---
apiVersion: v1
kind: Namespace
metadata:
  name: verdaccio
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: verdaccio-data
  namespace: verdaccio
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: verdaccio
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: verdaccio
  releaseName: verdaccio
  chart:
    spec:
      chart: verdaccio
      version: '4.17.0'
      sourceRef:
        kind: HelmRepository
        name: verdaccio
        namespace: flux-system
      interval: 12h
  values:
    persistence:
      enabled: true
      existingClaim: verdaccio-data
