---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfs-provisioner
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./deploy
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: nfs-provisioner
  targetNamespace: nfs-provisioner
  timeout: 3m0s
  wait: true
  patches:
    - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          labels:
            app: nfs-client-provisioner
          name: nfs-client-provisioner
        spec:
          template:
            spec:
              containers:
                - name: nfs-client-provisioner
                  env:
                    - name: NFS_SERVER
                      value: 192.168.4.124
                    - name: NFS_PATH
                      value: /volume1/ClusterStorage/
              volumes:
                - name: nfs-client-root
                  nfs:
                    server: 192.168.4.124
                    path: /volume1/ClusterStorage/
      target: 
        name: nfs-client-provisioner
        kind: Deployment
    - patch: |-
        - op: add
          path: /parameters/pathPattern
          value: ${.PVC.namespace}-${.PVC.name}
        - op: add
          path: /parameters/archiveOnDelete
          value: "true"
      target: 
        name: nfs-client
        kind: StorageClass