---
apiVersion: v1
kind: Namespace
metadata:
  name: nfs-provisioner
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nfs-provisioner
  namespace: nfs-provisioner
spec:
  interval: 10m0s
  ref:
    branch: master
  url: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner
