apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/asustor

patches:
  - target:
      kind: HTTPRoute
      name: asustor
      namespace: asustor
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: asustor.local.non-prod.abbottland.io
  - target:
      kind: HTTPRoute
      name: asustor-http-to-https
      namespace: asustor
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: asustor.local.non-prod.abbottland.io
