apiVersion: v1
kind: ConfigMap
metadata:
  namespace: media
  name: gluetun-auth-config
data:
  auth.toml: |
    [[roles]]
    name = "public"
    auth = "none"
    routes = [
      "GET /v1/portforward",
    ]
