apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: radarr
  name: radarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - image: lscr.io/linuxserver/radarr:latest
          name: radarr
          envFrom:
            - configMapRef:
                name: servarr-env
          env:
            - name: RADARR__POSTGRES__HOST
              value: "nas.local.abbottland.io"
            - name: RADARR__POSTGRES__PORT
              value: "5432"
            - name: RADARR__POSTGRES__USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: RADARR__POSTGRES__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: RADARR__POSTGRES__MAINDB
              value: "radarrdb"
            - name: RADARR__POSTGRES__LOGDB
              value: "radarrlogdb"
            - name: RADARR__POSTGRES__CACHEDB
              value: "radarrcachedb"
          volumeMounts:
            - name: radarr-config
              mountPath: /config
            - name: media-pvc
              mountPath: "/data"
          resources: {}
          ports:
            - containerPort: 7878
              hostPort: 7878
              name: httpa
              protocol: TCP
      volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: media-pvc
          persistentVolumeClaim:
            claimName: media-pvc
