apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonarr
  name: sonarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  strategy: {}
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - image: lscr.io/linuxserver/sonarr:latest
          name: sonarr
          envFrom:
            - configMapRef:
                name: servarr-env
          env:
            - name: SONARR__POSTGRES__HOST
              value: "nas.local.abbottland.io"
            - name: SONARR__POSTGRES__PORT
              value: "5432"
            - name: SONARR__POSTGRES__USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: SONARR__POSTGRES__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: SONARR__POSTGRES__MAINDB
              value: "sonarrdb"
            - name: SONARR__POSTGRES__LOGDB
              value: "sonarrlogdb"
          volumeMounts:
            - name: sonarr-config
              mountPath: /config
            - name: media-pvc
              mountPath: "/data"
          resources: {}
          ports:
            - containerPort: 8989
              hostPort: 8989
              name: httpa
              protocol: TCP
      volumes:
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: media-pvc
          persistentVolumeClaim:
            claimName: media-pvc
