apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: kube-system
  releaseName: metrics-server
  chart:
    spec:
      chart: metrics-server
      version: "3.x"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      interval: 12h
  values:
    args:
      - --kubelet-insecure-tls
    priorityClassName: system-cluster-critical
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        memory: 512Mi
