apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./arc
  - ./asustor
  - ./blog
  - ./dashy
  - ./diagram-maker
  - ./fui-components
  - ./flux-gitops
  - ./haproxy
  - ./harbor
  - ./media
  - ./pihole
  - ./plex
  - ./podinfo
  - ./proxmox
