---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: harbor-admin-secret
  namespace: harbor
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/Homelab/items/harbor.local.abbottland.io - admin"
