---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: harbor-db-secret
  namespace: harbor
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/Homelab/items/harbor-db-secret"
