apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-secrets
  namespace: harbor
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    adminPassword: AgBIzeLsTKuPBdbsmPFpgVwOjWFJDxwCxRKXMvxDxsMR/sEn+NR7DdfkfT5Dx8NElpoWVHDc1WRYRXIr4rEsbZHYjP9o8AZBsTXAW9hW1gsQNHE3f7lvn1g4vG8WiB0UjprsQWSQtTl3oqGKo1nykWKyZPCxFUU5/AQbLs9nsmHYAypXtaIZjarQejuJlTA28hBhNY+zV1tq/0FLHWKviBqPxyS/XgkwYPmYwkOWp/gh0J8EOMSwRg+EttWlNxr7yUdugzuLKfcU7i9HmKFwRQXUwfSML9ZZ9UdAF0yHDar34eZWm6HsJp2c8StIc1+sOo6HbTmNrl8pRgBMSBcyxB6WxHwcEaQZz+VYTYsY2Ay2LpFH1vEi5dl7xzKsAXbHs3HPLEwQpEQlVfXabEeSybWIesyVVB9MuG3VDzKt2TslGLfiRyMR/OsgYd7ciV89H0mMth0NXcoWJ/boieb9blxBvzYFuYE3CCn9J+ej+e13tji4goJISPi15m46tGxeOIY7Zjcv4kKOB8OwNyTYu1UMmYcS2l0LOWmdL5Gt/xdHndPZTGixzGawX2+vyJTgTsPuPvyuvBYxW8DsNc7pNQhkmiljtSUff77rMQuDLRraKdJ5GkPfTEgmX+jnZlqzWGZbVTnST8fDdnIwJyhDHd/ebBCG52YFTDGe3LrM4ixBg9L3JnOIOdkicVb6+SGMuimuB2OZR0LX5Y/Ub2htNgQ=
