---
apiVersion: v1
kind: Namespace
metadata:
  name: harbor
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: harbor
  releaseName: harbor
  chart:
    spec:
      chart: harbor
      version: '1.15.0'
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
      interval: 12h
  values:
    existingSecretAdminPassword: harbor-secrets
    existingSecretAdminPasswordKey: adminPassword
    redis:
      internal:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - dumbledore
    core:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: NotIn
                  values:
                    - dumbledore
    persistence:
      enabled: true
      resourcePolicy: keep
      persistentVolumeClaim:
        registry: 
          storageClass: nfs-client
        jobservice:
          jobLog:
            storageClass: nfs-client
        database:
          storageClass: nfs-client
        redis:
          storageClass: nfs-client
        trivy:
          storageClass: nfs-client
    externalUrl: harbor.local.abbottland.io
    expose:
      type: ingress
      tls:
        enabled: true
        certSource: secret
        secret:
          secretName: harbor-tls
      ingress:
        hosts:
          core: harbor.local.abbottland.io
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,192.168.0.0/16,172.20.0.0/12,10.244.0.0/16
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
