apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/proxmox

patches:
  - target:
      kind: HTTPRoute
      name: proxmox
      namespace: proxmox
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: proxmox.local.non-prod.abbottland.io
  - target:
      kind: HTTPRoute
      name: proxmox-http-to-https
      namespace: proxmox
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: proxmox.local.non-prod.abbottland.io
  - target:
      kind: AuthorizationPolicy
      name: proxmox-ingress-ip-allowlist
      namespace: istio-system
    patch: |-
      - op: replace
        path: /spec/rules/0/to/0/operation/hosts/0
        value: proxmox.local.non-prod.abbottland.io
      - op: replace
        path: /spec/rules/1/to/0/operation/notHosts/0
        value: proxmox.local.non-prod.abbottland.io
