apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/proxmox

patches:
  - target:
      kind: HTTPRoute
      name: proxmox
      namespace: proxmox
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: proxmox.local.non-prod.abbottland.io
  - target:
      kind: HTTPRoute
      name: proxmox-http-to-https
      namespace: proxmox
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: proxmox.local.non-prod.abbottland.io
