---
apiVersion: v1
kind: Namespace
metadata:
  name: home-assistant
---

apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: home-assistant
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8123
---

apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  namespace: home-assistant 
  # by convention, use the name of the Service
  # as a prefix for the name of the EndpointSlice
  name: homeassistant-1
  labels:
    kubernetes.io/service-name: homeassistant
addressType: IPv4
ports:
  - name: http 
    appProtocol: http
    protocol: TCP
    port: 8123
endpoints:
  - addresses:
      - "192.168.4.24"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 10m0s
  dependsOn:
    - name: infra-config
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./templates/ingress/base/
  prune: true
  wait: true
  timeout: 5m0s
  targetNamespace: home-assistant
  postBuild:
    substitute:
      ingress_name: home-assistant
      ingress_host: homeassistant.abbottland.io
      ingress_service_name: homeassistant
      ingress_service_port: "8123"
      ingress_configuration_snippet: ''
