---
apiVersion: v1
kind: Namespace
metadata:
  name: home-assistant
---

apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8123
---

apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  # by convention, use the name of the Service
  # as a prefix for the name of the EndpointSlice
  name: home-assistant-1
  namespace: home-assistant 
  labels:
    kubernetes.io/service-name: home-assistant
addressType: IPv4
ports:
  - name: http 
    appProtocol: http
    protocol: TCP
    port: 8123
endpoints:
  - addresses:
      - "192.168.4.24"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  namespace: home-assistant
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - homeassistant.abbottland.io
      secretName: podinfo-tls
  rules:
  - host: homeassistant.abbottland.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: home-assistant
            port:
              number: 8123
