apiVersion: longhorn.io/v1beta1
kind: Node
metadata:
  name: k8s-worker-1
  namespace: longhorn
spec:
  allowScheduling: true
  disks:
    ssd-disk:
      allowScheduling: true
      diskDriver: ""
      diskType: filesystem
      evictionRequested: false
      path: /mnt/longhorn-ssd
      storageReserved: 0
      tags: []
  evictionRequested: false
  instanceManagerCPURequest: 0
  name: k8s-worker-1
  tags: []