---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dashy-item-icons
  namespace: dashy
spec:
  storageClassName: nas-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi