---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dashy-item-icons-fast
  namespace: dashy
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi