resources:
  - ./dashy-deployment.yaml
  - ./dashy-icons-pvc-fast.yaml
  - ./dashy-ingress.yaml
  - ./dashy-namespace.yaml
  - ./dashy-service.yaml

configMapGenerator:
- name: dashboard-config
  namespace: dashy
  files:
    - conf.yml