---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: media
  name: gluetun-sync-config
data:
  PORT: "4000"
  GLUETUN_API_HOST: http://localhost:8000
  QBITTORRENT_API_HOST: http://localhost:8080
  QBITTORRENT_USERNAME: admin
