---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: media
  labels:
    app: gluetun
  name: gluetun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gluetun
  template:
    metadata:
      labels:
        app: gluetun
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: NotIn
                  values:
                  - arm64
      containers:
        - name: curl-container
          image: quay.io/curl/curl:latest
          command: ["sleep", "infinity"]

        - image: qmcgaw/gluetun
          name: gluetun
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          ports:
            - containerPort: 8000
              hostPort: 8000
              name: api
              protocol: TCP
            - containerPort: 8888
              hostPort: 8888
              name: http-proxy
              protocol: TCP
            - containerPort: 8388
              name: shadowsocks-tcp
              protocol: TCP
            - containerPort: 8388
              name: shadowsocks-udp
              protocol: UDP
          env:
            - name: TZ
              value: "America/Chicago"
            - name: VPN_SERVICE_PROVIDER
              value: "private internet access"
            - name: SERVER_REGIONS
              value: "CA Toronto"
            - name: PORT_FORWARD_ONLY
              value: "true"
            - name: VPN_PORT_FORWARDING
              value: "on"
            - name: FIREWALL_INPUT_PORTS
              value: "8000"
          envFrom:
            - secretRef:
                name: gluetun-secrets
          volumeMounts:
            - name: dev-net-tun
              mountPath: "/dev/net/tun"
            - name: gluetun-config
              mountPath: /gluetun
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
        - name: gluetun-config
          persistentVolumeClaim:
            claimName: gluetun-config


