---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gluetun-config
  namespace: media
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi