apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: gluetun-sync
  namespace: flux-system
spec:
  image: harbor.local.abbottland.io/library/gluetun-sync
  interval: 5m
  secretRef:
    name: regcred