---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: pia-credentials
  namespace: media
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/Homelab/items/PrivateInternetAccess.com"
