apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
  namespace: media
spec:
  capacity:
    storage: 10Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nfs:
    server: 192.168.4.124 
    path: "/volume1/Media"