---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-pvc
  namespace: media
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti