---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prowlarr-config
  namespace: media
spec:
  storageClassName: nas-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi