

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: media
  name: gluetun-sync-config
data:
  PORT: "4000"
  GLUETUN_API_HOST: http://localhost:8000
  QBITTORRENT_API_HOST: http://localhost:8080
  QBITTORRENT_USERNAME: admin
  QBITTORRENT_PASSWORD: password123
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: media
  name: gluetun-config
data:
  TZ: America/Chicago
  VPN_SERVICE_PROVIDER: "private internet access"
  SERVER_REGIONS: "CA Toronto"
  PORT_FORWARD_ONLY: "true"
  VPN_PORT_FORWARDING: "on"
  # 8888 - gluetun http proxy (included by default)
  # 8388 - gluetun shadowsocks-tcp (included by default)
  # 8000 - gluetun api
  # 8080 - qbittorrent ui
  # 6881 - ~~qbittorrent torrents~~ (DONT WANT)
  # 4000 - gluetun-sync status check
  FIREWALL_INPUT_PORTS: "8000,8080,4000"

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: media
  name: qbit-env
data:
  PUID: "1000"
  PGID: "1000"
  TZ: America/Chicago
  WEBUI_PORT: "8080"
  TORRENTING_PORT: "6881"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: media
  labels:
    app: qbittorrent-vpn
  name: qbittorrent-vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent-vpn
  template:
    metadata:
      labels:
        app: qbittorrent-vpn
        api: gluetun
    spec:
      imagePullSecrets:
        - name: regcred
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: NotIn
                  values:
                  - arm64
      containers:
        - name: gluetun-sync
          image: harbor.local.abbottland.io/library/gluetun-sync:latest
          imagePullPolicy: Always
          resources: {}
          ports:
            - containerPort: 4000
              hostPort: 4000
              name: sync-api
              protocol: TCP
          envFrom:
            - configMapRef:
                name: gluetun-sync-config

        - name: curl-container
          image: quay.io/curl/curl:latest
          command: ["sleep", "infinity"]
          resources: {}

        - image: qmcgaw/gluetun
          name: gluetun
          resources: {}
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          ports:
            - containerPort: 8000
              hostPort: 8000
              name: api
              protocol: TCP
            - containerPort: 8888
              hostPort: 8888
              name: http-proxy
              protocol: TCP
            - containerPort: 8388
              name: shadowsocks-tcp
              protocol: TCP
            - containerPort: 8388
              name: shadowsocks-udp
              protocol: UDP
          envFrom:
            - configMapRef:
                name: gluetun-config
            - secretRef:
                name: gluetun-secrets
          volumeMounts:
            - name: dev-net-tun
              mountPath: "/dev/net/tun"
            - name: gluetun-config
              mountPath: /gluetun

        - image: lscr.io/linuxserver/qbittorrent:latest
          name: qbittorrent
          resources: {}
          ports:
            - containerPort: 8080
              name: web
          envFrom:
            - configMapRef:
                name: qbit-env
          volumeMounts:
            - name: media-downloads
              mountPath: "/downloads"
            - name: qbit-config
              mountPath: /config
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
        - name: gluetun-config
          persistentVolumeClaim:
            claimName: gluetun-config
        - name: media-downloads
          persistentVolumeClaim:
            claimName: media-downloads
        - name: qbit-config
          persistentVolumeClaim:
            claimName: qbit-config

