apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent-secrets
  namespace: media
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    QBITTORRENT_PASSWORD: 'AgCX5paJDL+kdbKVRHwP15k0BMHGYarQci5HAhTogng/bGhQiGR2shWvO5Tti0TwXln7TGjPycqTlI3YHBf+hqebsb4CahU63SWeOu50FReGV2nq85HUXnOAEEii0wcLzFio9+u2hvoFfpP6Kr4J4AAdAWek5KVf6uwWfOVT/Ikt4yMDtPNkBtvCwuRZJwyF0mhbz6V+NhoFXAssr7Ix10M3td330aejfuumFYHW1j6zZ4RN7oUIF3oQLMzQzgUan2D+npuZn76Ff1mCncW95ggjPI4dfWMAy4Ncc87WA0Yx9FM0Zh45AgWxzvPPwJ0kQRl6eKLn5I8kkaQ43M7YL618sn6Bs+sEbZNzSsxl7vSxiJ7nTGC/m0BmFx/Zeo5sIHvCcHZFcKzoLZy2hlUl4Gxk3jGLgIwRAkbYOTXJhylv6jRlNv5HN6dwbRrrZEXfAV6T8S+U5WASkMMrZvSAlgLBoUgq8KX8CYXmpBCOv3ef9Va2uYmlk+EIEdXVBQQOEdJ0m3L2+bnO0TljxDIySuXFnrGGXx74r/BuzGakVm8AhdwMjDSbKMhRWcw9QrKo/LiNOmaZpOeuUgMMF/g+2juwdGPVhY3ROUp9t3N+d7CNAkePF5oOVHtv/71YdxEV3D8Lo1t3P5E4Jj7OuvsEHARQz8/FzBlorEsZ84T4e1qJBEY1lYO+QuhfrG49bSBdxOmvXKPtFH5dA55TWNEtiDc='
