
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: media
  labels:
    app: qbittorrent
  name: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - image: lscr.io/linuxserver/qbittorrent:latest
          name: qbittorrent
          ports:
            - containerPort: 8080
              name: web
            - containerPort: 6881
              name: torrents
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Chicago"
            - name: WEBUI_PORT
              value: "8080"
            - name: TORRENTING_PORT
              value: "6881"
          volumeMounts:
            - name: media-downloads
              mountPath: "/downloads"
            - name: qbit-config
              mountPath: /config
      volumes:
        - name: media-downloads
          persistentVolumeClaim:
            claimName: media-downloads
        - name: qbit-config
          persistentVolumeClaim:
            claimName: qbit-config


