---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-ui
  namespace: media
  labels:
    app: qbittorrent-vpn
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: qbittorrent-vpn