---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: qbittorrent-credentials
  namespace: media
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/Homelab/items/qbittorrent.local.abbottland.io"
