apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent-secrets
  namespace: media
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    QBITTORRENT_PASSWORD: 'AgAWGA8XpFEDpHH7YbgZ9+DNHTEf8kB0i1tfDWLD9RvMuEq7cUThVuRvBYFkLmPQ45l6g9dVtD42UUDePQCO+Yz+LOxADIpy9rrwy2+kS0g8Y8d54dHfg41hXSZU1g2j1s2FDmHgbAuxNw/9XTQtJqLy4s/XKOB0jD08qvqH/gdQ2k1sFX7NiXZpja+61A/cQNUI3lHMm6MwI64W+Na4I81tlXzFhFCgL6wNQgvRIUKZ/3JhsEUurJMmqeBlWHGU/c7oAEIdlc53IzzoejT6WGZpmHdpBIBwEaDd2Y9/5We+QF9FeUaYOxwTUsZvIEYRYxMuazeq0xC+6rWPWqGJGZz2sJr1Fd60ELEjH7gcxhqKXV72cn7Cb1WCupSVx2aj2/i5KcPXLIH4allPZCKqtz3KAZ7O8LdZ3ZJUIZnZITl+7i/qxPJfsr9mD0ttRIuV4mObS2JSTG6BOV2WShxh0YyEvi7OH398t9Wq1fkaatjQ3oapyA7GuZW1gktUqcWuWMQlHEdlHVlj8s56O4bi4/kcvA40G4rCL1h8UUQ5Ky1FA2raTfxmXlK41oOPMN/iuiJALupvAB+Iq6jTWhm2LgOJc4/eT4L/IkR6ZtXb0c2K6ePeXyq+TS5SHKHzzs46ASsaEtrluPTCtzFjChDMhbrueYTIKmtv1V028qWPyj0VIY0MNLbDmsVmRyTy1CsFGkWPDIAHffF1djEMEULUw/c='
