kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: regcred
  namespace: home-hud
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  template:
    metadata:
      name: regcred
      namespace: home-hud
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
    type: kubernetes.io/dockerconfigjson
  encryptedData:
    .dockerconfigjson: AgCCMcDhB+wK4gDeQv7mrNsWKXWZucrcMkeXbi71bOGnzWXHCApIgpGvk14W8qIk1n7mSG5u0tN7ayq2ZM8ysXS+tu4FX1SNwbKm5RHkPEQF5Yz8sHCPwkTy30DHjS/ASORxEQ10gQSaJ7bVvhcUQRpmrxy2jwywBofGK5UUNi1JOLHtTOMWQ/55cdSrVa2d+IXzaLKtLSJHAg719xrUiVDeAozPlbVfqsrwj+mmvihPkxASsLSKnI28zpGklAxs/4LgTPDLrX+LDjq5U8xZl0tUgk/rn6GXcJNGYNFxiqNuAF91HBp3M/y+e/flo8theJULZLczVEp5PhWZ03dbjlTq4VLhDLv/BMD8laWUXzzlVrlr8wZ5UuSaNOo71revFm1Qb57ZPjC740pI8VB9U2r/T285Kn1DB8D3bzMN3wboqaTamWZO/9kj5SeD8UynvFprrjYtgxuNQswG75M1y7Mn93pJ52SHb8ffeB9Q8zKZ3dQR4f50R5z5Kw7QhneqzK8JWsDfnWzy0Ya1mlUwcGE+IeSQZfabgXQA8GyMDyhnQL27Vbb6fD2EmkG48Zc33vpqHF4l9gRtyF62fKN0wr6htvcpdycktGjZmTEuYgHvuP6qJfgH4HkFbFENdvZQ8UnBDuLgtvahlfS5rAh/vd0oM6rWSjHYnNH1MPH42nTgfrx9xpsRnJED7xZR2yDMx80nJK1sJXMY2472SKN/Oxp1MAWsuOMdl9HUpOGOLDXsHNX9C7b8A+eyGq0y1Ubgh2fkVq+yY9RFYyFaFW0ExysHSajB0IDXXC70wcTE6QY32+z+ucju94fSteh+uyUT8d1OUzdQUGq4t/IpdF/bMZzPnVgrNWc0gWlG662yjacCalzGIB/C+vEye0CcXeYZe5HBoc/8fFXWYf6/MezjITipPArqzgHcgTVFWnvrf9Wm4w==
