apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: op-connect
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: op-connect
  releaseName: op-connect
  chart:
    spec:
      chart: connect
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: flux-system
      version: 1.17.0
  values:
    sync:
      serviceType: ClusterIP
      
    connect:
      create: true
      credentialsName: op-credentials
      credentialsKey: 1password-credentials.json
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,192.168.0.0/16,172.20.0.0/12,10.244.0.0/16
        ingressClassName: nginx
        hosts:
        - host: op-connect.local.abbottland.io
          paths:
          - backend:
              service:
                name: op-connect
                port:
                  number: 8080
            path: /
            pathType: Prefix
        tls:
        - hosts:
          - op-connect.local.abbottland.io
          secretName: op-connect
      
    operator:
      create: true
      token:
        name: op-credentials
        key: token
    