---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: falcondev-oss-charts
  namespace: flux-system
spec:
  type: oci
  interval: 24h
  url: oci://ghcr.io/falcondev-oss/charts
