---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: arc-listeners
  namespace: arc-systems
  labels:
    release: monitoring
spec:
  podMetricsEndpoints:
    - port: metrics
      interval: 1m
      scrapeTimeout: 30s
      scheme: http
      relabelings:
        - targetLabel: job
          replacement: arc-listeners
  selector:
    matchLabels:
      app.kubernetes.io/component: runner-scale-set-listener
  namespaceSelector:
    matchNames:
      - arc-systems
