---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: arc-runners
  namespace: arc-runners
spec:
  hard:
    pods: "20"
    limits.cpu: "28"
    limits.memory: 80Gi
    limits.ephemeral-storage: 200Gi
