---
apiVersion: v1
kind: LimitRange
metadata:
  name: arc-runners
  namespace: arc-runners
spec:
  limits:
    - type: Container
      default:
        cpu: "2"
        memory: 4Gi
        ephemeral-storage: 20Gi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 1Gi
