---
apiVersion: v1
kind: LimitRange
metadata:
  name: arc-runners
  namespace: arc-runners
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 2Gi
        ephemeral-storage: 5Gi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 1Gi
