---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: arc-runners
  namespace: arc-runners
spec:
  hard:
    pods: "25"
    limits.cpu: "32"
    limits.memory: 100Gi
    limits.ephemeral-storage: 200Gi
