---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-runner-amd64
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: arc-runners
  releaseName: non-prod-gen2-amd64-runner
  dependsOn:
    - name: arc-controller
  chart:
    spec:
      chart: gha-runner-scale-set
      version: '0.14.1'
      sourceRef:
        kind: HelmRepository
        name: gha-runner-scale-set-charts
        namespace: flux-system
      interval: 12h
  values:
    githubConfigUrl: https://github.com/pbabbott/home-web-apps
    githubConfigSecret: arc-gh-secret
    runnerScaleSetName: non-prod-gen2-amd64-runner
    minRunners: 1
    maxRunners: 3
    runnerGroup: default
    listenerTemplate:
      spec:
        containers:
          - name: listener
        dnsConfig:
          options:
            - name: ndots
              value: "2"
    template:
      spec:
        dnsConfig:
          options:
            - name: ndots
              value: "2"
        nodeSelector:
          kubernetes.io/arch: amd64
        containers:
          - name: runner
            image: ghcr.io/actions/actions-runner:latest
            command: ["/home/runner/run.sh"]
            resources:
              requests:
                cpu: "1"
                memory: "1Gi"
                ephemeral-storage: "1Gi"
              limits:
                cpu: "2"
                memory: "2.5Gi"
                ephemeral-storage: "10Gi"
        priorityClassName: arc-runner-low
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: non-prod-gen2-dind-runner
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  topologyKey: kubernetes.io/hostname
                  labelSelector:
                    matchExpressions:
                      - key: longhorn.io/component
                        operator: In
                        values: ["instance-manager"]
        topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: runner
                app.kubernetes.io/instance: non-prod-gen2-amd64-runner
