---
apiVersion: v1
kind: Service
metadata:
  name: arc-controller-metrics
  namespace: arc-systems
  labels:
    app.kubernetes.io/name: gha-rs-controller
    app.kubernetes.io/instance: arc-controller
spec:
  selector:
    app.kubernetes.io/name: gha-rs-controller
    app.kubernetes.io/instance: arc-controller
    app.kubernetes.io/component: controller-manager
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
