apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - arc-systems-ns.yaml
  - arc-runners-ns.yaml
  - gha-runner-scale-set-charts-helmrepository.yaml
  - arc-controller-helmrelease.yaml
  - arc-runner-amd64-helmrelease.yaml
  - arc-runner-dind-amd64-helmrelease.yaml
  - arc-runners-resourcequota.yaml
  - arc-runners-limitrange.yaml
  - arc-pnpm-store-persistentvolumeclaim.yaml
  - actions-cache-server-helmrepository.yaml
  - actions-cache-server-helmrelease.yaml
  - turborepo-remote-cache-helmrepository.yaml
  - turbo-cache-storage-persistentvolumeclaim.yaml
  - turborepo-remote-cache-helmrelease.yaml
