---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: turbo-cache-storage
  namespace: arc-runners
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
