apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/kube-prometheus-stack

patches:
  - path: kube-prometheus-stack-helm-release-patch.yaml
  - target:
      kind: HTTPRoute
      name: prometheus-ui
      namespace: kube-prometheus-stack
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: prometheus.local.abbottland.io
  - target:
      kind: HTTPRoute
      name: grafana-ui
      namespace: kube-prometheus-stack
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: grafana.local.abbottland.io

configMapGenerator:
  - name: grafana-dashboard-kubernetes-cluster-overview
    namespace: kube-prometheus-stack
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
    files:
      - dashboards/kubernetes-cluster-overview.json
