---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo-ingress-public
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infra-config
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./templates/ingress/base/
  prune: true
  wait: true
  timeout: 5m0s
  targetNamespace: default
  postBuild:
    substitute:
      ingress_name: podinfo-public
      ingress_host: podinfo.abbottland.io
      ingress_service_name: podinfo
      ingress_service_port: "9898"
      ingress_configuration_snippet: ''