apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key-secret
  namespace: cert-manager
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    api-token: "AgBTBHNS+fFu2kvfewZaHQ5cbq105ZRKS+9DImNe8orG2qXHiJujI8ULuv5+2fUWeTbDKDFWX9oLc/eBglrRwNtCvFic+93L2zMuWYLbsJIF3MeOCqwsDTcq64JCR3x8MULFgqaMWfwljDjSkEJM1uvG6eCykCsi5sCthpXMrUbS6X3XTQzbjtYqY8gEQSK4jhx/KcElasS3RquhlCWCX9JZ16wL53fZqiCemLv2OlUH33LoPF4AVLQ2IvIgESapskSQYrhuYPTK0MSfwUBzsCkrEkFs/16BdjReogVAHncU3i7jwge2WeTuAV7USxYWwIFlbdLaWMYbkOQRDOknEbrmaJ6qFBDP9FOhNa1/n55xCFn+XlFlXAr3RXdCwiuvVX3LuG1D8/2h+RimM+WZ9Gr54OQ6Qje/C/GiYQPDOFyLJRAlYJ46GZ2sjlw90BIb1GIziAyUhC3pWnzcdBVCxaE4AnVXSo2k9NmD3Hyd3ruHi8rWSVEZagi8s76+O/34ZeuH7Ij9USOJ8Ew0Cawf/6kqnQo+cQIg1zdLe3RfsVs1hErZ2Aw56f93fBKuqwBbmtPlA+EBHbPRcG6LrbOsWgzZ4uhG4SbvxPzYsuq7XUPweyR87+jRtm8CJEbro+SnxlAfIw211cqwNy/TBUtazmBvjdlqo8RCrzM2G+db8v7rhCdyC+6JOJYLuEClPbFeYuPMz8LCU9bc1oBT/Ce273Lj8UCI4VlyAW7Ov8R12GKZ0I4CCc97xljy"
