apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key-secret
  namespace: external-dns
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    api-token: AgCUV/hApIKYxOBQBCtsDBeno/3Vs/NhWc/8r+R22qlDyAWiqMw5fptJ0uRmBsFAJ94TM0+l+4rLncLZsubi+mu0qwE4yL+PLcpXiMOtUIIg6n0IeK8pGp3TfXsw0II4Xx+dwJAg2qany0AG0d4/HQmGkcRwPtohlOxTWFPjPJ/X8wUVSmFZ/DFJFXEP3c+YXIYIrivWUwcR8fUs3EjiUrQu42mkp4fXI/Y7X+cl23K3+tR2LQPKC13LTWNj81bJVWl17aMYWetPJcum9AWRHp3dn46YQhR+AeRRU0sdhAXZToqEgEmW2kiuglAt27zFI+0UmdkWODZePHjQjOy/zMNDT6QOzZ+MF65qI+V4jnH5JJbTJK2Gup7qz582j+OvOOuz0Rcdpz9xoAP++5nJ6B3Y3Ep4IPuFTSJ7JDLeW245Pu0n8hcntAkKzaBFCS+Nwob4Z93mdH8joAOCRaeRMwws02hET8/NPUHzFkFbMOIcKl1spmhggum/pjZFqKuSk6XXdRunGPZaOXpZE35ojwjnsHDC/i6mrao2Vv3YSJIBifHDH4Bk7CpJRdXA9+p2StloM/Snz/ON9Zg7SbS8PlaMwbwSLjr3V2j67LjpmgaEkI0tegXY+BYXGcQSg/eo+4uD6KPY720SuQ1lvhMcrwiF8ee3/oMmm/uUPLfgwb3SZAvXYIKRVGEzvuhk3Q+j+cq83NI+A6xs3PTud1nNSyAWaP+0hBzimuu+gmjUVJpRrnWQ9SZE5srQ
