apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blog
  namespace: blog
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: blog
  endpoints:
    - port: http
      path: /api/metrics
      interval: 60s
  namespaceSelector:
    matchNames:
      - blog
