apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - regcred-onepassworditem.yaml
  - blog-image-repository.yaml
  - blog-image-policy.yaml
  - blog-deployment.yaml
  - blog-service.yaml
  - blog-httproute.yaml
  - blog-http-to-https-httproute.yaml
