---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drone
  namespace: drone
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
  - host: drone.abbottland.io
    http:
      paths:
      - backend:
          service:
            name: drone
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - drone.abbottland.io
    secretName: drone-tls
