apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/nas-storage

patches:
  - target:
      kind: HelmRelease
      name: nas-storage
      namespace: flux-system
    patch: |-
      - op: replace
        path: /spec/values/nfs/path
        value: /volume1/ClusterStorage/prod-gen2
