apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./cert-manager-cloudflare-secret.yaml
  - ./cert-manager-helm-release.yaml
  - ./cert-manager-helm-repo.yaml
  - ./cert-manager-namespace.yaml
