apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key-secret
  namespace: external-dns
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    cloudflare_api_token: AgA6moByFd/iAT2deTprLhQrdBRWmVbErfy3Kqec8vmnNdvVkjBOUuDcMuQat9ucP/A+dZQQTK3/XAf1+xcMB4w+W7t8Te5f2+Lu8VDWmnYCYZfD3ButuneEv96fIJa7huPtwaajk78braF5nhC1TZbwWYGjBlzD6OdyTqAt5buxOE4+oJ/FkkJ32FMI5IjGOxjOCGQkS3m3m5Y9Hc12hhseRI3ia9HU8M0yRsAaP6CDgkdO/NJfjHTxaKpF5wOnCLh4+paVgnMzKFh2VwdmnJbvXzcN+TVVkm/W2mhWVVWtZnkXLMNDGeCa39E9Omraq8KD3FNwNxRMWcE1Ub9TmUA0dc6rjyJhU+d8r3FvZ/YdJVX+Zm00JFai5qY14p1tiWg7UlxpbsngcW2Dm0bKavlp91z9F7AcyIAKh3vSBDZKbpi/JnKd3wS92z9mv64EurWfJdbmTr4MWuVwvMgaUzLsj4N0RGHjXZEqHemtp2t5qwHTptaoM1DUzY2jW1vkoEECPAyZ2bkKNQeckJlKcGgN3qdI0yLFsF0xD5zx6RgXqRnAEKt+BS3vOD6qf30HKBRTkwWmKZfaAlShxhbwsd1YPdbkeU++PVTFHm+eJj/v7v2AMvr9kja2aO6GIveHBFlRhRasqGZrUFqfj6GKa0HrbTkKNjRQpQaKbllCy9XJbdvXJ5+omeNjyZEE7ExqbOlt1p8/h8MaAABcYqW0bpA4o9tIxWTazzisls3DkgaE2qe1ab1E77yV
