apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: external-dns
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 8.7.1 # TODO: fix this once external-dns chart 1.15.1 becomes available.
  values:
    labelFilter: external-dns-enabled=true
    provider: cloudflare
    cloudflare:
      secretName: cloudflare-api-token-secret
      proxied: true
    domainFilters:
      - abbottland.io
    managedRecordTypesFilters:
    - CNAME
    sources:
      - ingress
    policy: "sync"
    