apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      version: 1.13.0 # Use the latest version
  values:
    provider: cloudflare
    cloudflare:
      apiTokenSecretRef:
        name: cloudflare-api-key-secret
        key: token
    domainFilters:
      - abbottland.io
    txtOwnerId: external-dns
    logLevel: info
    policy: upsert-only
