apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: external-dns
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      version: 1.15.0
  values:
    labelFilter: external-dns-enabled=true
    provider:
      name: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-key-secret
            key: api-token
    domainFilters:
      - abbottland.io
    managedRecordTypes:
    - CNAME
    sources:
      - ingress
    policy: "sync"
    