apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dashy
  namespace: flux-system
spec:
  targetNamespace: dashy
  chart:
    spec:
      chart: ./applications/base/dashy
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 30m
  values:
    hostname: dashy.local.non-prod.abbottland.io
    pageTitle: "Homelab (non-prod)"
    urls:
      pihole: https://pihole.local.non-prod.abbottland.io/admin/
      haproxy: https://haproxy.local.non-prod.abbottland.io
      proxmox: https://proxmox.local.non-prod.abbottland.io
      asustor: https://asustor.local.non-prod.abbottland.io
      flux: https://flux.local.non-prod.abbottland.io
      longhorn: https://longhorn.local.non-prod.abbottland.io
      prometheus: https://prometheus.local.non-prod.abbottland.io
      grafana: https://grafana.local.non-prod.abbottland.io
      harbor: https://harbor.local.non-prod.abbottland.io
      podinfoLocal: https://podinfo.local.non-prod.abbottland.io/
      podinfoPublic: http://podinfo.non-prod.abbottland.io/
