
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: '4.10.1'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 12h
  values:
    controller:
      kind: DaemonSet
      allowSnippetAnnotations: true
      config:
        use-proxy-protocol: "true"
        proxy-real-ip-cidr: "192.168.4.144"
        enable-real-ip: "true"
        use-forwarded-headers: "true"
        ssl-redirect: "true"
        force-ssl-redirect: "true"
      proxySetHeaders:
        X-Frame-Options: "SAMEORIGIN"
        X-XSS-Protection: "1; mode=block"
        X-Content-Type-Options: "nosniff"
        Strict-Transport-Security: "max-age=15552000; includeSubDomains; preload"
      addHeaders:
        Upgrade: "$http_upgrade"
        Connection: upgrade
      service:
        externalTrafficPolicy: "Local"
        type: NodePort
        nodePorts:
          http: 30080
          https: 30443

# TODO:
# nginx.ingress.kubernetes.io/x-forwarded-proto: "https"