
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: ingress-nginx
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: '4.10.1'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 12h
  values:
    controller:
      metrics:
        enabled: true
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
      kind: DaemonSet
      allowSnippetAnnotations: true
      config:
        enable-real-ip: "true"
        force-ssl-redirect: "true"
        proxy-real-ip-cidr: "192.168.4.144"
        ssl-redirect: "true"
        use-forwarded-headers: "true"
        use-proxy-protocol: "true"
        x-forwarded-proto: "https"
      proxySetHeaders:
        X-Frame-Options: "SAMEORIGIN"
        X-XSS-Protection: "1; mode=block"
        X-Content-Type-Options: "nosniff"
        Strict-Transport-Security: "max-age=15552000; includeSubDomains; preload"
      addHeaders:
        Upgrade: "$http_upgrade"
        Connection: upgrade
      service:
        externalTrafficPolicy: "Local"
        type: NodePort
        nodePorts:
          http: 30080
          https: 30443

# TODO:
# nginx.org/websocket-services: "websockettest-cluster-ip-service"