---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 30m
  chart: ingress-nginx
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: ingress-nginx
    namespace: flux-system
  version: '4.*'