apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./ingress-nginx-helm-chart.yaml
  - ./ingress-nginx-helm-release.yaml
  - ./ingress-nginx-helm-repo.yaml
  - ./ingress-nginx-ns.yaml
  - ./ingress-nginx-service-monitor.yaml
