---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 10m0s
  dependsOn:
    - name: infra-config
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./templates/ingress/overlays/internal-ingress
  prune: true
  wait: true
  timeout: 5m0s
  targetNamespace: prometheus
  postBuild:
    substitute:
      ingress_name: prometheus
      ingress_host: prometheus.local.abbottland.io
      ingress_service_name: prometheus-k8s
      ingress_service_port: "9090"
      ingress_configuration_snippet: ''
  commonMetadata:
    annotations:
      nginx.org/websocket-services: "websockettest-cluster-ip-service"
      nginx.ingress.kubernetes.io/x-forwarded-proto: "https"
