---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-crds
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./manifests/setup
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: kube-prometheus
  timeout: 3m0s
  wait: true
---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus
  namespace: flux-system
spec:
  interval: 30m0s
  dependsOn:
    - name: kube-prometheus-crds
      namespace: flux-system
  path: ./manifests
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: kube-prometheus
  timeout: 3m0s
  wait: true