apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/arc
  - arc-gh-secret.yaml
  - arc-controller-servicemonitor.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/releaseName
        value: prod-gen2-amd64-runner
      - op: replace
        path: /spec/values/runnerScaleSetName
        value: prod-gen2-amd64-runner
      - op: replace
        path: /spec/values/maxRunners
        value: 5
      - op: replace
        path: /spec/values/template/spec/affinity/podAntiAffinity/requiredDuringSchedulingIgnoredDuringExecution
        value: []
      - op: replace
        path: /spec/values/template/spec/topologySpreadConstraints/0/whenUnsatisfiable
        value: ScheduleAnyway
      - op: replace
        path: /spec/values/template/spec/topologySpreadConstraints/0/labelSelector/matchLabels/app.kubernetes.io~1instance
        value: prod-gen2-amd64-runner
      - op: replace
        path: /spec/values/template/spec/containers/0/resources/limits/memory
        value: "4Gi"
    target:
      kind: HelmRelease
      name: arc-runner-amd64
  - patch: |-
      - op: replace
        path: /spec/releaseName
        value: prod-gen2-dind-runner
      - op: replace
        path: /spec/values/runnerScaleSetName
        value: prod-gen2-dind-runner
      - op: replace
        path: /spec/values/maxRunners
        value: 5
      - op: replace
        path: /spec/values/template/spec/affinity/podAntiAffinity/requiredDuringSchedulingIgnoredDuringExecution
        value: []
      - op: replace
        path: /spec/values/template/spec/topologySpreadConstraints/0/whenUnsatisfiable
        value: ScheduleAnyway
      - op: replace
        path: /spec/values/template/spec/topologySpreadConstraints/0/labelSelector/matchLabels/app.kubernetes.io~1instance
        value: prod-gen2-dind-runner
      - op: replace
        path: /spec/values/template/spec/containers/0/resources/limits/memory
        value: "3Gi"
      - op: replace
        path: /spec/values/template/spec/containers/1/resources/limits/memory
        value: "5Gi"
    target:
      kind: HelmRelease
      name: arc-runner-dind-amd64
