apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: turbo-cache-token
  namespace: arc-runners
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/Homelab/items/turbo-cache-token"
