apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/sealed-secrets
  - ./onepassword
  - ./cert-manager
  - ./istio
  - ./flux-operator
  - ./longhorn
  - ./nas-storage
  - ./kube-prometheus-stack
  - ../base/metrics-server
  - ../base/priorityclass
  - ./pihole
  - ./external-dns
