hostname: dashy.local.non-prod.abbottland.io

urls:
  pihole: https://pihole.local.non-prod.abbottland.io/admin/
  haproxy: https://haproxy.local.non-prod.abbottland.io
  proxmox: https://proxmox.local.non-prod.abbottland.io
  asustor: https://asustor.local.non-prod.abbottland.io
  flux: https://flux.local.non-prod.abbottland.io
  longhorn: https://longhorn.local.non-prod.abbottland.io
  prometheus: https://prometheus.local.non-prod.abbottland.io
  grafana: https://grafana.local.non-prod.abbottland.io
