apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./cert-manager
  - ./grafana
  - ./longhorn-system
  - ./monitoring
  - ./nas-storage
  - ./bitnami-helm-repo.yaml
  - ./patch-core-dns-configmap.yaml
  - ./sealed-secrets-helm-release.yaml
  - ./sealed-secrets-helm-repo.yaml
