---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: kube-system
  releaseName: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      version: '2.15.4'
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
      interval: 12h
  values:
    fullnameOverride: sealed-secrets-controller