apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: github-pat
  namespace: harbor-cleanup
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/Homelab/items/Github PAT"
