apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-cleanup-config
  namespace: harbor-cleanup
data:
  HARBOR_HOST: "harbor.local.abbottland.io"
  GITHUB_OWNER: "pbabbott"
  GITHUB_REPO: "home-web-apps"
  CLEANUP_REPOSITORIES: "blog,diagram-maker,fui-components,gluetun-sync,harbor-cleanup"
  CLEANUP_CRON_EXPRESSION: "0 3 * * *"
  TZ: "America/Chicago"
  PROD_KEEP_COUNT: "5"
