apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: harbor-cleanup-pod-reader
subjects:
  - kind: ServiceAccount
    name: harbor-cleanup
    namespace: harbor-cleanup
roleRef:
  kind: ClusterRole
  name: harbor-cleanup-pod-reader
  apiGroup: rbac.authorization.k8s.io
