apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - regcred-onepassworditem.yaml
  - harbor-credentials-onepassworditem.yaml
  - github-pat-onepassworditem.yaml
  - harbor-cleanup-serviceaccount.yaml
  - harbor-cleanup-clusterrole.yaml
  - harbor-cleanup-clusterrolebinding.yaml
  - harbor-cleanup-configmap.yaml
  - harbor-cleanup-image-repository.yaml
  - harbor-cleanup-image-policy.yaml
  - harbor-cleanup-deployment.yaml
  - harbor-cleanup-service.yaml
  - harbor-cleanup-httproute.yaml
  - harbor-cleanup-http-to-https-httproute.yaml
  - harbor-cleanup-servicemonitor.yaml
