apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/cert-manager

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cloudflare-ddns
        namespace: cert-manager
        $patch: delete
    target:
      kind: Deployment
      name: cloudflare-ddns
      namespace: cert-manager
