apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/podinfo

patches:
  - target:
      kind: HTTPRoute
      name: podinfo
      namespace: podinfo
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: podinfo.local.non-prod.abbottland.io
  - target:
      kind: HTTPRoute
      name: podinfo-http-to-https
      namespace: podinfo
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: podinfo.local.non-prod.abbottland.io
  - target:
      kind: HTTPRoute
      name: podinfo-public
      namespace: podinfo
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: podinfo.non-prod.abbottland.io
      - op: remove
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1cloudflare-proxied
      - op: replace
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
        value: non-prod.abbottland.io
  - target:
      kind: HTTPRoute
      name: podinfo-public-http-to-https
      namespace: podinfo
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: podinfo.non-prod.abbottland.io
      - op: remove
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1cloudflare-proxied
      - op: replace
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
        value: non-prod.abbottland.io
