apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/podinfo/namespace.yaml
  - ../../base/podinfo/helmrepository.yaml
  - ../../base/podinfo/helmrelease.yaml
  - ../../base/podinfo/podinfo-httproute.yaml
  - ../../base/podinfo/podinfo-http-to-https-httproute.yaml

patches:
  - target:
      kind: HTTPRoute
      name: podinfo
      namespace: podinfo
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: podinfo.local.non-prod.abbottland.io
  - target:
      kind: HTTPRoute
      name: podinfo-http-to-https
      namespace: podinfo
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: podinfo.local.non-prod.abbottland.io
