apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - podinfo-httproute.yaml
  - podinfo-http-to-https-httproute.yaml
  - podinfo-public-httproute.yaml
  - podinfo-public-http-to-https-httproute.yaml
