apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/flux-operator

patches:
  - target:
      kind: HelmRelease
      name: flux-operator
      namespace: flux-system
    patch: |-
      - op: replace
        path: /spec/values/web/httpRoute/hostnames/0
        value: flux.local.abbottland.io
