apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: arc-actions-runner-controller
  namespace: arc
  labels:
    release: monitoring
spec:
  endpoints:
    - port: metrics-port
      interval: 1m
      scrapeTimeout: 30s
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      app.kubernetes.io/name: actions-runner-controller
      app.kubernetes.io/instance: arc
  namespaceSelector:
    matchNames:
      - arc
