
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: arc
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: arc
  releaseName: arc
  chart:
    spec:
      chart: actions-runner-controller
      version: '0.23.7'
      sourceRef:
        kind: HelmRepository
        name: arc
        namespace: flux-system
      interval: 12h