---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: arc
  namespace: flux-system
spec:
  interval: 24h
  url: https://actions-runner-controller.github.io/actions-runner-controller

