apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: fui-components
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: fui-components
  filterTags:
    pattern: '^\d{8}-\d+-[a-f0-9]{7}$'
  policy:
    alphabetical:
      order: asc
