apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - jetstack-helm-repository.yaml
  - cloudflare-api-token-onepassword.yaml
  - cert-manager-helm-release.yaml
  - cluster-issuers.yaml
