apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    version: "2.8.x"
    registry: ghcr.io/fluxcd
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
    - image-reflector-controller
    - image-automation-controller
  cluster:
    type: kubernetes
    multitenant: false
    networkPolicy: true
    domain: cluster.local
  sync:
    kind: GitRepository
    url: ssh://git@github.com/pbabbott/home-kubernetes
    ref: refs/heads/main
    path: clusters/prod-gen2
    pullSecret: flux-system
    interval: 5m
  kustomize:
    patches:
      - patch: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: placeholder
          spec:
            template:
              spec:
                dnsConfig:
                  options:
                    - name: ndots
                      value: "1"
        target:
          kind: Deployment
          labelSelector: "app.kubernetes.io/part-of=flux"
