apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/istio

patches:
  - target:
      kind: Gateway
      name: istio-ingress
      namespace: istio-system
    patch: |-
      - op: replace
        path: /spec/listeners/1/hostname
        value: "*.local.non-prod.abbottland.io"
      - op: replace
        path: /spec/listeners/1/tls/certificateRefs/0/name
        value: wildcard-local-non-prod-tls
  - target:
      kind: Gateway
      name: istio-ingress-public
      namespace: istio-system
    patch: |-
      - op: replace
        path: /spec/listeners/0/hostname
        value: "*.non-prod.abbottland.io"
      - op: replace
        path: /spec/listeners/0/tls/certificateRefs/0/name
        value: wildcard-public-non-prod-tls
      - op: replace
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1target
        value: non-prod.abbottland.io
