apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/istio

patches:
  - target:
      kind: Gateway
      name: istio-ingress
      namespace: istio-system
    patch: |-
      - op: replace
        path: /spec/listeners/1/hostname
        value: "*.local.non-prod.abbottland.io"
      - op: replace
        path: /spec/listeners/1/tls/certificateRefs/0/name
        value: wildcard-local-non-prod-tls
  - patch: |-
      apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      metadata:
        name: istio-ingress-public
        namespace: istio-system
        $patch: delete
    target:
      kind: Gateway
      name: istio-ingress-public
      namespace: istio-system
