apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/istio/hsts-envoyfilter.yaml
  - ../../base/istio/global-authorizationpolicy.yaml
  - ../../base/istio/istio-cni-helm-release.yaml
  - ../../base/istio/istio-cni-pod-monitor.yaml
  - ../../base/istio/istiod-helm-release.yaml
  - ../../base/istio/istiod-service-monitor.yaml
  - ../../base/istio/istio-ingress-gateway-api.yaml
  - ../../base/istio/istio-ingress-helm-release.yaml
  - ../../base/istio/istio-ingress-pod-monitor.yaml
  - ../../base/istio/ztunnel-helm-release.yaml
  - ../../base/istio/ztunnel-pod-monitor.yaml

patches:
  - target:
      kind: Gateway
      name: istio-ingress
      namespace: istio-system
    patch: |-
      - op: replace
        path: /spec/listeners/1/hostname
        value: "*.local.non-prod.abbottland.io"
      - op: replace
        path: /spec/listeners/1/tls/certificateRefs/0/name
        value: wildcard-local-non-prod-tls
