apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: external-nodes
  namespace: monitoring
  labels:
    prometheus: k8s
spec:
  staticConfigs:
    - labels:
        job: node-exporter
        instance: bananapi
        service: node-exporter
      targets:
        - bananapi.local.abbottland.io:9100
    - labels:
        job: node-exporter
        instance: chimaera
        service: node-exporter
      targets:
        - chimaera.local.abbottland.io:9100
    - labels:
        job: node-exporter
        instance: room_of_requirement
        service: node-exporter
      targets:
        - nas.local.abbottland.io:9100
            