apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/arc
  - arc-gh-secret.yaml
  - arc-controller-servicemonitor.yaml
  - turbo-cache-token-onepassworditem.yaml
  - turborepo-cache-httproute.yaml
