apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kubelet-csr-approver
  namespace: kube-system
spec:
  interval: 24h
  url: https://postfinance.github.io/kubelet-csr-approver
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubelet-csr-approver
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: kubelet-csr-approver
      sourceRef:
        kind: HelmRepository
        name: kubelet-csr-approver
        namespace: kube-system
      interval: 12h
  values:
    providerRegex: '^k8s-$'
    providerIpPrefixes: '192.168.4.0/22'
    maxExpirationSeconds: '86400'
    bypassDnsResolution: 'false'
