---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns-pihole
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-admin-password # change secret name
  namespace: external-dns-pihole # change namespace name
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgDd4UHVJI510Z2s64oL70gZ22aeLKVgsT2Ls/8ChNF0JdiTqphWSBCK7zDeEKe3llQPXyjn6aUBZIuxK76U5vxmT6ZD6f5vKQChcQMmjUwzG8tgCsMjgvX/bFJWGl4qYifrL8G7a5EpW46s4wScev331e7wiggGB1BYJ40Gm1/a72qqyzDov/Mxp09jtN24N3lfBVXo3f/nDoXolIR08EZtAX0Iy1YeqYTHAVqv4sSjdi+4feLDCyTiWfmHwwJcURamBT/qesoYR8mjqH4zTGUwo38upuFMnU/7VepRlrpZkTht7o0dwuThDQeYfNEBC/SOb3OGIak1Gj5qG4B6duF0z6nQ/AO3yTrEcBTCA6qiItZ6E1cR4/na1Zcdz3iIHbuL0CCrKl6Sk8fLrdcxLx2gK7oB717pPASf/a/Tiq8GJGeGSwCcry1W3UaqK27lxA3HOFrJrvth5ixcsbsGnEy4j1fQQGqC02Js91HY8JaEkygBN1l5dk7Nbfz66D20IrFGdh6GGQhCzT2oQeej/ZzC96icidRfpP7i6Utt4CQ2ObT0L4bbW9gDgHge5E0MzdnaSfe9DZZenCr/Z/e85I9nZr/kLkFZII5FXSaVHkiKr2o8mv96z13++JO8f66tYacQLFpvX2qRcWi+kEynbaLvaf9nXuOlLnAuH1/Sz+tvqAGykhDk08U446l8EIlIsfMtr5AOqx66Vz5ntO94LGibQcA/96ZLhPIEN0MVpg==
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: external-dns-pihole
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions","networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: external-dns-pihole
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns-pihole
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.14.2
        envFrom:
        - secretRef:
            name: pihole-admin-password
        args:
        # - --source=service
        - --source=ingress
        # Pihole only supports A/AAAA/CNAME records so there is no mechanism to track ownership.
        # You don't need to set this flag, but if you leave it unset, you will receive warning
        # logs when ExternalDNS attempts to create TXT records.
        - --registry=noop

        # IMPORTANT: If you have records that you manage manually in Pi-hole, set
        # the policy to upsert-only so they do not get deleted.
        - --policy=upsert-only
        - --provider=pihole
        - --pihole-server=http://192.168.4.144:8081

        # Pihole will only be used for internal DNS entries
        - --annotation-filter=abbottland.io/dns.class=internal
      securityContext:
        fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes token files