---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns-pihole
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-admin-password # change secret name
  namespace: external-dns-pihole # change namespace name
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgANCsz00GzDDi8n1RNzrra632hFsN5WXiYPHJ4lUf1skHaqziRmAV0B1EkYALpM+tdc+txyRczQoBGCl2yq5pmBR1srUNtKgVZqlIzs86Hw/l9cYORIGn87LERaQGX9xjl/GHEPQceuCOz3Mr9b8xDvHK+940L5WbUapadMgw0eS3kl00GeEQivlPjoPa5iKHuUPktj6DIcnbKZG0TL35uSqTb0aFTKtCHqA7LmhrBIUq0HSZmmimZal+SvZ4RBbQ/Uyktv1FSQdyQXQabnoEz11Gv+J21I4RFc9MX7jZskB55MiNi5pBimkQhsceS3HsiUrYj2+d4gbpYw0wX6jdITfyRbhMeb8QJqOxOxDSumVXsG6LUWQ989dJO5n1Q3D3FqOUMV2lqxW1E/g7yqN3x75MZRMEPHzXm05KvKBMSQbDAsp4xNfb8ikSBRQk5/oOQYzgUckBk+XnRBH6BXAOtV5XbZxJ2vH990y1QwmRCL+NT/wlr4Ux8UOHj6z05K4tmkMC2nXAcWkwhLcqKulhkqy3rqWt0ZKP/42C6VtkzCICFmRTotCJ/iXFxwqiwSSCX7a39Hyp8iH+WReZS5Q/LzSnPCUykajJUuU+xLnYQwGlYzXxRvx7mFrVR7nw+EtpBamHmoRla2cMdUEcMPvNpM9EEWwf0nrtcXCU/GQSism7ttBBqsQZLr5M3Yd0IAL/Wp0XgiOAX76lcgajZzl68IKE6Zu0uxjh829ccRlA==
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: external-dns-pihole
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions","networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: external-dns-pihole
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns-pihole
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.14.2
        envFrom:
        - secretRef:
            name: pihole-admin-password
        args:
        # - --source=service
        - --source=ingress
        # Pihole only supports A/AAAA/CNAME records so there is no mechanism to track ownership.
        # You don't need to set this flag, but if you leave it unset, you will receive warning
        # logs when ExternalDNS attempts to create TXT records.
        - --registry=noop

        # IMPORTANT: If you have records that you manage manually in Pi-hole, set
        # the policy to upsert-only so they do not get deleted.
        - --policy=upsert-only
        - --provider=pihole
        - --pihole-server=http://192.168.4.144:8081

        # Pihole will only be used for internal DNS entries
        - --label-filter=internal
      securityContext:
        fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes token files