---
apiVersion: v1
kind: Namespace
metadata:
  name: metrics-server
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/metrics-server/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  interval: 30m
  chart:
    spec:
      chart: metrics-server
      version: '3.12.1'
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: metrics-server
      interval: 12h
  values:
    replicaCount: 1
    args: 
      - --kubelet-insecure-tls