apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: flux-system
spec:
  releaseName: grafana-operator
  targetNamespace: grafana
  chart:
    spec:
      chart: grafana-operator
      version: 5.17.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 30m
  values:
    serviceMonitor:
      # -- Whether to create a ServiceMonitor
      enabled: true