---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack-crds
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: kube-prometheus-stack
  releaseName: kube-prometheus-stack-crds
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '70.*'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: true
  values:
    crds:
      enabled: true
    prometheusOperator:
      enabled: false
    prometheus:
      enabled: false
    alertmanager:
      enabled: false
    grafana:
      enabled: false
    kubeStateMetrics:
      enabled: false
    nodeExporter:
      enabled: false
    thanosRuler:
      enabled: false
    kubeApiServer:
      enabled: false
    kubelet:
      enabled: false
    kubeControllerManager:
      enabled: false
    coreDns:
      enabled: false
    kubeDns:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
