apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: uptime-kuma
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: uptime-kuma
  policy:
    semver:
      range: 1.x.x