apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: postgres-credentials
  namespace: coder
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/Homelab/items/PostgreSQL NAS ASUSTOR"
