apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - coder-ns.yaml
  - coder-helmrepository.yaml
  - coder-db-helmrepository.yaml
  - coder-db-helmrelease.yaml
  - coder-helmrelease.yaml
  - coder-httproute.yaml
  - coder-http-to-https-httproute.yaml
