apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - coder-ns.yaml
  - coder-helmrepository.yaml
  - coder-postgres-credentials-onepassworditem.yaml
  - coder-helmrelease.yaml
  - coder-httproute.yaml
  - coder-http-to-https-httproute.yaml
  - coder-workspaces-ns.yaml
  - coder-workspaces-role.yaml
  - coder-workspaces-rolebinding.yaml
