apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/istio

patches:
  - target:
      kind: Gateway
      name: istio-ingress
      namespace: istio-system
    patch: |-
      - op: replace
        path: /spec/listeners/1/hostname
        value: "*.local.abbottland.io"
      - op: replace
        path: /spec/listeners/1/tls/certificateRefs/0/name
        value: wildcard-local-tls
