---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: kube-prometheus-stack
  releaseName: kube-prometheus-stack
  dependsOn:
    - name: kube-prometheus-stack-crds
      namespace: flux-system
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '70.*'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 12h
  install:
    crds: Skip
  upgrade:
    crds: Skip
  values:
    crds:
      enabled: false
    alertmanager:
      enabled: false
    grafana:
      enabled: true
      adminPassword: admin
      grafana.ini:
        date_formats:
          default_timezone: America/Chicago
      readinessProbe:
        timeoutSeconds: 10
      livenessProbe:
        timeoutSeconds: 10
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
          labelValue: "1"
          searchNamespace: ALL
    defaultRules:
      enabled: true
    kubeStateMetrics:
      enabled: true
    kubeApiServer:
      enabled: true
    kubelet:
      enabled: true
    kubeControllerManager:
      enabled: false
    coreDns:
      enabled: true
    kubeDns:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
    prometheus-node-exporter:
      livenessProbe:
        timeoutSeconds: 5
      readinessProbe:
        timeoutSeconds: 5
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}
        podMonitorSelectorNilUsesHelmValues: false
        podMonitorSelector: {}
        podMonitorNamespaceSelector: {}
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1500Mi
        storageSpec:
          volumeClaimTemplate:
            metadata:
              labels:
                recurring-job-group.longhorn.io/default: disabled
            spec:
              storageClassName: longhorn
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 20Gi
        retention: 3d
