apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - kube-prometheus-stack-helm-release.yaml
  - prometheus-httproute.yaml
  - grafana-httproute.yaml

configMapGenerator:
  - name: grafana-dashboard-my-hosts
    namespace: kube-prometheus-stack
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
    files:
      - dashboards/my-hosts.json
  - name: grafana-dashboard-kubernetes-cluster-overview
    namespace: kube-prometheus-stack
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
    files:
      - dashboards/kubernetes-cluster-overview.json
  - name: grafana-dashboard-longhorn
    namespace: kube-prometheus-stack
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
    files:
      - dashboards/longhorn.json
  - name: grafana-dashboard-harbor
    namespace: kube-prometheus-stack
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
    files:
      - dashboards/harbor.json
  - name: grafana-dashboard-haproxy
    namespace: kube-prometheus-stack
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
    files:
      - dashboards/haproxy.json
