apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mcp-grafana-ns.yaml
  - mcp-grafana-secret-onepassworditem.yaml
  - mcp-grafana-deployment.yaml
  - mcp-grafana-service.yaml
  - mcp-grafana-netpol.yaml
  - mcp-grafana-httproute.yaml
