{
 "title": "My Host Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "nodename",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},nodename)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "  sum by(nodename) (avg without (mode,cpu)(1- rate(node_cpu_seconds_total{mode=\"idle\", job=\"$job\"}[5m])) * on(instance) group_left(nodename) node_uname_info{job=\"$job\"})",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (nodename) (((node_memory_MemTotal_bytes{job=\"$job\"}-node_memory_MemFree_bytes{job=\"$job\"}-node_memory_Buffers_bytes{job=\"$job\"}-node_memory_Cached_bytes{job=\"$job\"}) / node_memory_MemTotal_bytes{job=\"$job\"}) * on(instance) group_left(nodename) node_uname_info{job=\"$job\"}) ",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Disk Space Used% Basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((\r\n    node_filesystem_size_bytes{job=\"$job\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}\r\n    -node_filesystem_free_bytes{job=\"$job\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}\r\n) * 100 \r\n/(\r\n    node_filesystem_avail_bytes {job=\"$job\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}\r\n    + (\r\n        node_filesystem_size_bytes{job=\"$job\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}\r\n        - node_filesystem_free_bytes{job=\"$job\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}\r\n    )\r\n)) * on (instance) group_left(nodename) node_uname_info {job=\"$job\", nodename=\"$nodename\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "${nodename}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "nodename" },
  {
   "title": "Instance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{nodename=\"$nodename\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - (node_boot_time_seconds{job=\"$job\"} * on (instance) group_left(nodename) node_uname_info {job=\"$job\", nodename=\"$nodename\"}))"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{job=\"$job\", mode='system'}* on (instance) group_left(nodename) node_uname_info {job=\"$job\", nodename=\"$nodename\"})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"$job\"} * on (instance) group_left(nodename) node_uname_info {job=\"$job\", nodename=\"$nodename\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "bargauge",
   "description": "Used Root FS",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\n(\n  ((node_filesystem_size_bytes{job=\"$job\", mountpoint=\"/\", fstype!=\"rootfs\"}\n   - node_filesystem_avail_bytes{job=\"$job\", mountpoint=\"/\", fstype!=\"rootfs\"})\n  / node_filesystem_size_bytes{job=\"$job\", mountpoint=\"/\", fstype!=\"rootfs\"}) * on (instance) group_left(nodename) node_uname_info {job=\"$job\", nodename=\"$nodename\"}\n) * 100"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Percentage of filesystem space used for each mounted device",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(((node_filesystem_size_bytes{job=\"$job\", device!~\"rootfs\"} - node_filesystem_avail_bytes{job=\"$job\", device!~\"rootfs\"}) / node_filesystem_size_bytes{job=\"$job\", device!~\"rootfs\"}) * 100) * on (instance) group_left(nodename) node_uname_info {job=\"$job\", nodename=\"$nodename\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  (1 - sum without (mode) (rate(node_cpu_seconds_total{job=\"$job\", mode=~\"idle|iowait|steal\"}[5m])\n)\n\n)\n/ ignoring(cpu) group_left\n  count without (cpu, mode) (node_cpu_seconds_total{job=\"$job\", mode=\"idle\"}) * on (instance) group_left(nodename) node_uname_info {job=\"$job\", nodename=\"$nodename\"}\n)\n",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "RAM and swap usage overview, including caches",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{job=\"$job\"} - node_memory_MemFree_bytes{job=\"$job\"} - (node_memory_Cached_bytes{job=\"$job\"} + node_memory_Buffers_bytes{job=\"$job\"} + node_memory_SReclaimable_bytes{job=\"$job\"}))* on (instance) group_left(nodename) node_uname_info {job=\"$job\", nodename=\"$nodename\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "(node_memory_Cached_bytes{job=\"$job\"} + node_memory_Buffers_bytes{job=\"$job\"} + node_memory_SReclaimable_bytes{job=\"$job\"}) * on (instance) group_left(nodename) node_uname_info {job=\"$job\", nodename=\"$nodename\"}",
     "legendFormat": "Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"$job\"}* on (instance) group_left(nodename) node_uname_info {job=\"$job\", nodename=\"$nodename\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=\"$job\"} - node_memory_SwapFree_bytes{job=\"$job\"}) * on (instance) group_left(nodename) node_uname_info {job=\"$job\", nodename=\"$nodename\"}",
     "legendFormat": "Swap used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$job\"} * on (instance) group_left(nodename) node_uname_info {job=\"$job\", nodename=\"$nodename\"}",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}