apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-staging-pvc
  namespace: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
