apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
  namespace: plex
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
  - host: plex.abbottland.io
    http:
      paths:
      - backend:
          service:
            name: plex
            port:
              number: 32400
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - plex.abbottland.io
    secretName: plex-tls
