---
apiVersion: v1
kind: Namespace
metadata:
  name: asustor
---

apiVersion: v1
kind: Service
metadata:
  name: asustor
  namespace: asustor
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9000
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  namespace: asustor
  # by convention, use the name of the Service
  # as a prefix for the name of the EndpointSlice
  name: asustor-1
  labels:
    kubernetes.io/service-name: asustor
addressType: IPv4
ports:
  - name: http 
    appProtocol: http
    protocol: TCP
    port: 9000
endpoints:
  - addresses:
      - "192.168.4.124"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: asustor
  namespace: asustor
spec:
  interval: 10m0s
  dependsOn:
    - name: infra-config
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./templates/ingress/overlays/internal-ingress
  prune: true
  wait: true
  timeout: 5m0s
  targetNamespace: asustor
  postBuild:
    substitute:
      ingress_name: asustor
      ingress_host: asustor.abbottland.io
      ingress_service_name: asustor
      ingress_service_port: "9000"