---
apiVersion: v1
kind: Namespace
metadata:
  name: dashy
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dashy-item-icons
  namespace: dashy
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dashy
  labels:
    app: dashy
  name: dashy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashy
  template:
    metadata:
      labels:
        app: dashy
    spec:
      containers:
        - image: lissy93/dashy:latest
          name: dashy
          ports:
            - containerPort: 8080
              hostPort: 8080
              name: http
          volumeMounts:
            - mountPath: "/app/public/item-icons"
              name: dashy-item-icons
      volumes:
        - name: dashy-item-icons
          persistentVolumeClaim:
            claimName: dashy-item-icons
          
---
apiVersion: v1
kind: Service
metadata:
  name: dashy
  namespace: dashy
  labels:
    app: dashy
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: dashy
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dashy
  namespace: dashy
spec:
  interval: 10m0s
  dependsOn:
    - name: infra-config
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./templates/ingress/overlays/internal-ingress
  prune: true
  wait: true
  timeout: 5m0s
  targetNamespace: dashy
  postBuild:
    substitute:
      ingress_name: dashy
      ingress_host: dashboard.local.abbottland.io
      ingress_service_name: dashy
      ingress_service_port: "8080"
