---
apiVersion: v1
kind: Namespace
metadata:
  name: dashy
---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dashy-ingress
  namespace: dashy
spec:
  interval: 10m0s
  dependsOn:
    - name: infra-config
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./templates/internal-ingress/
  prune: true
  wait: true
  timeout: 5m0s
  targetNamespace: dashy
  postBuild:
    substitute:
      ingress_name: dashy
      ingress_host: dashy.local.abbottland.io
      ingress_service_name: dashy
      ingress_service_port: "3000"
