---
apiVersion: v1
kind: Namespace
metadata:
  name: pihole
---

apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: pihole
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  namespace: pihole
  # by convention, use the name of the Service
  # as a prefix for the name of the EndpointSlice
  name: pihole-1
  labels:
    kubernetes.io/service-name: pihole
addressType: IPv4
ports:
  - name: http 
    appProtocol: http
    protocol: TCP
    port: 8081
endpoints:
  - addresses:
      - "192.168.4.144"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Frame-Options "SAMEORIGIN";
      add_header X-XSS-Protection "1; mode=block";
      add_header X-Content-Type-Options "nosniff";
      add_header Strict-Transport-Security "max-age=15552000; includeSubDomains; preload";
      add_header Upgrade $http_upgrade;
      add_header Connection "upgrade";
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-proxy-protocol: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,192.168.0.0/16,172.20.0.0/12,10.244.0.0/16
    nginx.ingress.kubernetes.io/rewrite-target: /admin/$1
  name: pihole
  namespace: pihole
spec:
  ingressClassName: nginx
  rules:
  - host: pihole.local.abbottland.io
    http:
      paths:
      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: pihole
            port:
              number: 8081
  tls:
  - hosts:
    - pihole.local.abbottland.io
    secretName: pihole-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Frame-Options "SAMEORIGIN";
      add_header X-XSS-Protection "1; mode=block";
      add_header X-Content-Type-Options "nosniff";
      add_header Strict-Transport-Security "max-age=15552000; includeSubDomains; preload";
      add_header Upgrade $http_upgrade;
      add_header Connection "upgrade";
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-proxy-protocol: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,192.168.0.0/16,172.20.0.0/12,10.244.0.0/16
    nginx.ingress.kubernetes.io/permanent-redirect: /
    nginx.ingress.kubernetes.io/permanent-redirect-code: "301"
  name: pihole-redirect
  namespace: pihole
spec:
  ingressClassName: nginx
  rules:
  - host: pihole.local.abbottland.io
    http:
      paths:
      - path: /admin
        pathType: Exact
        backend:
          service:
            name: pihole
            port:
              number: 8081
        
  tls:
  - hosts:
    - pihole.local.abbottland.io
    secretName: pihole-tls