---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./kustomize
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: default
  timeout: 3m0s
  wait: true
  patches:
    - patch: |-
        apiVersion: v1
        kind: Service
        metadata:
          name: podinfo
        spec:
          type: NodePort
          ports:
            - name: http
              port: 9898
              nodePort: 30100
              protocol: TCP
              targetPort: http
            - port: 9999
              targetPort: grpc
              protocol: TCP
              name: grpc
      target: 
        name: podinfo
        kind: Service
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 10m0s
  dependsOn:
    - name: infra-config
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./templates/ingress/overlays/internal-ingress
  prune: true
  wait: true
  timeout: 5m0s
  targetNamespace: default
  postBuild:
    substitute:
      ingress_name: podinfo
      ingress_host: podinfo.local.abbottland.io
      ingress_service_name: podinfo
      ingress_service_port: "9898"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo-public
  namespace: default
spec:
  interval: 10m0s
  dependsOn:
    - name: infra-config
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./templates/ingress/base/
  prune: true
  wait: true
  timeout: 5m0s
  targetNamespace: default
  postBuild:
    substitute:
      ingress_name: podinfo-public
      ingress_host: podinfo.abbottland.io
      ingress_service_name: podinfo
      ingress_service_port: "9898"
