---
apiVersion: v1
kind: Namespace
metadata:
  name: uptime-kuma
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: uptime-kuma-app-data
  namespace: uptime-kuma
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: uptime-kuma
  labels:
    app: uptime-kuma
  name: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
        - image: louislam/uptime-kuma:1
          name: uptime-kuma
          ports:
            - containerPort: 3001
              name: http
          volumeMounts:
            - mountPath: "/app/data"
              name: uptime-kuma-app-data
      volumes:
        - name: uptime-kuma-app-data
          persistentVolumeClaim:
            claimName: uptime-kuma-app-data
          
---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
  labels:
    app: uptime-kuma
spec:
  ports:
    - port: 3001
      protocol: TCP
  selector:
    app: uptime-kuma
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  interval: 10m0s
  dependsOn:
    - name: infra-config
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./templates/ingress/overlays/internal-ingress
  prune: true
  wait: true
  timeout: 5m0s
  targetNamespace: uptime-kuma
  postBuild:
    substitute:
      ingress_name: uptime-kuma
      ingress_host: kuma.local.abbottland.io
      ingress_service_name: uptime-kuma
      ingress_service_port: "3001"
  commonMetadata:
    annotations:
      nginx.org/websocket-services: "websockettest-cluster-ip-service"
