---
apiVersion: v1
kind: Namespace
metadata:
  name: uptime-kuma
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  interval: 10m0s
  dependsOn:
    - name: infra-config
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./templates/ingress/overlays/internal-ingress
  prune: true
  wait: true
  timeout: 5m0s
  targetNamespace: uptime-kuma
  postBuild:
    substitute:
      ingress_name: uptime-kuma
      ingress_host: kuma.local.abbottland.io
      ingress_service_name: uptime-kuma
      ingress_service_port: "3000"

# docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1
# docker run -d --restart=always -p 127.0.0.1:3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1
