---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: longhorn-instance-manager
  namespace: longhorn-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      longhorn.io/component: instance-manager
