---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: longhorn-system
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      version: '1.11.1'
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 12h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    defaultSettings:
      defaultDataPath: /mnt/ssd
    nodeSelector:
      kubernetes.io/arch: amd64
    longhornUI:
      replicas: 1
    ingress:
      enabled: false
    metrics:
      serviceMonitor:
        enabled: false
