---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: longhorn-system
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      version: '1.9.2'
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 12h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    defaultSettings:
      defaultDataPath: /mnt/ssd
      engineReplicaTimeout: 30
      priorityClass: system-node-critical
      replicaAutoBalance: best-effort
    nodeSelector:
      kubernetes.io/arch: amd64
    longhornManager:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
    longhornDriver:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 300m
          memory: 256Mi
    longhornInstanceManager:
      resources:
        requests:
          cpu: 200m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 384Mi
    longhornUI:
      replicas: 1
    ingress:
      enabled: false
    metrics:
      serviceMonitor:
        enabled: true
