apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: n8n
  releaseName: n8n
  chart:
    spec:
      chart: n8n
      version: '>=1.24.15'
      sourceRef:
        kind: HelmRepository
        name: community-charts
        namespace: flux-system
      interval: 12h
  values:
    postgresql:
      enabled: false
    redis:
      enabled: false
    externalPostgresql:
      host: nas.local.abbottland.io
      port: 5432
      database: n8n
      username: postgres
      existingSecret: postgres-credentials
      existingSecretPasswordKey: password
    existingEncryptionKeySecret: n8n-secret
    webhook:
      url: https://n8n.abbottland.io
    db:
      type: postgresdb
    main:
      extraEnvVars:
        N8N_ALLOW_EXEC_COMMAND: "true"
      volumes:
        - name: media
          nfs:
            server: 192.168.4.124
            path: /volume1/Media
      volumeMounts:
        - name: media
          mountPath: /data/media
