apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - ./arc  # temporarily disabled — nonprod cluster not running ARC runners
  - ./asustor
  - ./dashy
  - ./haproxy
  - ./harbor
  - ./plex
  - ./podinfo
  - ./proxmox
