apiVersion: v1
kind: Service
metadata:
  name: home-hud
  namespace: home-hud
  labels:
    app: home-hud
spec:
  selector:
    app: home-hud
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
