apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - home-hud-ns.yaml
  - postgres-credentials-onepassworditem.yaml
  - regcred-onepassworditem.yaml
  - media-pv.yaml
  - media-pvc.yaml
  - video-api-image-repository.yaml
  - video-worker-image-repository.yaml
  - home-hud-image-repository.yaml
  - video-api-deployment.yaml
  - video-api-service.yaml
  - video-api-httproute.yaml
  - video-api-netpol.yaml
  - video-worker-deployment.yaml
  - video-worker-service.yaml
  - video-worker-httproute.yaml
  - video-worker-netpol.yaml
  - home-hud-deployment.yaml
  - home-hud-service.yaml
  - home-hud-httproute.yaml
  - home-hud-netpol.yaml
