apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: sonarr-api-key
  namespace: home-hud
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/Homelab/items/SONARR_API_KEY"
