apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: video-api
  namespace: flux-system
spec:
  image: harbor.local.abbottland.io/library/video-api
  interval: 5m
  secretRef:
    name: regcred-flux
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: video-api
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: video-api
  filterTags:
    pattern: '^sha-[a-f0-9]+$'
  policy:
    alphabetical:
      order: asc
