apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: video-api
  namespace: home-hud
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: video-api
  endpoints:
    - port: http
      path: /metrics
      interval: 60s
  namespaceSelector:
    matchNames:
      - home-hud
