apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/external-dns

patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: external-dns
        namespace: flux-system
        $patch: delete
    target:
      kind: HelmRelease
      name: external-dns
      namespace: flux-system
  - patch: |-
      apiVersion: onepassword.com/v1
      kind: OnePasswordItem
      metadata:
        name: cloudflare-api-token-secret
        namespace: external-dns
        $patch: delete
    target:
      kind: OnePasswordItem
      name: cloudflare-api-token-secret
      namespace: external-dns
  - target:
      kind: HelmRelease
      name: external-dns-pihole
    patch: |-
      - op: replace
        path: /spec/values/domainFilters
        value: ["local.non-prod.abbottland.io"]
