apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/external-dns

patches:
  - target:
      kind: HelmRelease
      name: external-dns
    patch: |-
      - op: add
        path: /spec/values/txtOwnerId
        value: non-prod-gen2
      - op: add
        path: /spec/values/domainFilters
        value: ["non-prod.abbottland.io"]
  - target:
      kind: HelmRelease
      name: external-dns-pihole
    patch: |-
      - op: add
        path: /spec/values/txtOwnerId
        value: non-prod-gen2-pihole
      - op: replace
        path: /spec/values/domainFilters
        value: ["local.non-prod.abbottland.io"]
