apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/istio
  - ../base/gateway-api
  - ../base/cert-manager
  - ../base/flux-operator
  - ../base/sealed-secrets
  - ../base/onepassword
