apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: diagram-maker
  namespace: diagram-maker
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: diagram-maker
  endpoints:
    - port: http
      path: /api/metrics
      interval: 60s
  namespaceSelector:
    matchNames:
      - diagram-maker
