apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: diagram-maker
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: diagram-maker
  policy:
    semver:
      range: ">=0.0.0"
