apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - regcred-onepassworditem.yaml
  - diagram-maker-image-repository.yaml
  - diagram-maker-image-policy.yaml
  - diagram-maker-deployment.yaml
  - diagram-maker-service.yaml
  - diagram-maker-netpol.yaml
  - diagram-maker-public-httproute.yaml
