apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: regcred
  namespace: diagram-maker
  annotations:
    operator.1password.io/auto-restart: "true"
    operator.1password.io/type: "kubernetes.io/dockerconfigjson"
spec:
  itemPath: "vaults/Homelab/items/harbor.local.abbottland.io - admin"
