apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - istiod-helm-release.yaml
  - istio-cni-helm-release.yaml
  - ztunnel-helm-release.yaml
  - istio-ingress-helm-release.yaml
  - istio-ingress-gateway-api.yaml
  - istio-ingress-public-gateway-api.yaml
  - global-authorizationpolicy.yaml
  - istiod-service-monitor.yaml
  - istio-ingress-pod-monitor.yaml
  - ztunnel-pod-monitor.yaml
  - istio-cni-pod-monitor.yaml
