apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key-secret
  namespace: cert-manager
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    api-token: "AgCu4a7nq1sCMVP06G3CDYIOP/chanQEpf55ZOyaImXeg7ExfpouSkuVKdcsBm5tnC3doq4gOCZGyI2lZ1fcYiub25aCp0/w67gCazlY0YvZN1+6Wm6GD9pA50e8d9qm9jJpdssK01awZSR7KWUMZYAi09zfR7Hc+/Qy4FqK6G5MHwLwYPaxT2Q6TrOe54JiT3EpH2N46XeS+GvrWIZydJ/gLOvo5FuWnHDcuveGBJ/+TgRmtvUiLH7jQKkDTorRSTlKk/v6CwdXKJNuwaXk8nYxjrPtXOowaBA1qvR4xUq8yCAM76RKXewruBY9tJzdnu7hj7ZM/mzEAh3OgCWoWRhoRmrTs0anhz1DoN/2gPnejWIvnEeZXS/b3xwfrqvmv+uvY1sGIcQdKi2E6YYhQ7Arq70khh+UtjlqwPcunPzj2kKHmNenvQYStzHBISn5OWWrqemf0YXLMLFVe/7GFbM3s8Z7d/jhbMEYznaWLe4Jco+99Sna2A8fTZ/ucfZSLV97KFC1gEp5oZ5OhfDjAKCu2tkQidRxHB81vEbK5ZH4jH8ksT+KPwBFIilEveW1MN7YOsT0Qd8S9p76MphYoGQxmf2mlT/fvYagBSw1DNVCv84xpOxsOQNuOHk31WQmNB8VTkL9v+PQ9nQnodtMBkE3TR4FraQQpe6gYJsOKk6iBarURX8/z/AKyt+/2CeIE26/2iEGmxI+zPjBmhK2WgATh9MxuSJ72kTKvC8g10EyvCtx3XKS6Mhd"
