apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key-secret
  namespace: cert-manager
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    api-token: "AgAQ9oz+kCegttySCvm7QjGRTv2ipTstn0HQCSdeuCOy5NnHcrRQf6gPqDgG3gviTPw+iqFi9xDNfK7YYfstIn1ZHXA4Em12ujOK3CLVrfo2nZAdza+jiQX4yCYsUWnvMjfxlnMHkz1eTCBp04tWOYTxHhWZV4Sktc55UoVcfs2PgJfedMEoJyL/jeiNUjCL1GabCmincuVelUckbrq8zzxQ2kAaKH+KFkt+wKflVyWPVcK7lor8z7WIqmV4KRwoUvGCZUvEAioakdh7i7Do1fEiOm6SRNjIrjKjr6ndiC9wsQ9abcl5KJh3liML4mdjYP9Z8Bx3r0i97mQPYBM2XoMR56Co/hjIfrEShW2+ltL/X3jVtkNCKSGNXGZb4wrJMrw3iyEsnuEk/L8vHFpocGg7rcpXxGXzJ0S0rdOz3OdqHAGNNFYclsYSbFshz3z2P1K01l9+lkLtg94OxjrGS83284lmXNwz5mXjRg2/40SrIml6NPrjZSMtPQUpC49Qh4bbkIlw9kifuRQkDjpyiF5D5kap+qhdLG5xlfmaPBObq52ghg2n9c6rEk3yIOJh/bcQqHYjulO/ymfV/UI82pUu6DKgoaR8PKR/UNszh3j6ZzZ2//DAYbeY4PT82gVMsjtGGOpsVgOSgT+3YG2FXi4eUw2RTk7n1dA3ML4m049EQNz//mXu64KqaVkMtQIwHORNvXChdKf2kXu/SvUpljHXTjclKZxbiTDML9FVQfAYN7cmmDdrNsAe"
