apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key-secret
  namespace: cert-manager
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    api-token: "AgCldsrwAqtX3mI1cRMRpVbrxiNaeEqAVGORileZaN15dQtF6ryfFgvQig4r8X+coWWvJvRRxKBDavHOu6Ta9CW9/STcMhhIePHrZ2HaSqSkrQ9AnBvAkQhGWwUhCEKx2rszXOztsVkaX04JchGvyXdMBhedyrDQcSkC/O5knH0dMdTxG2i57pxl6kCBiWWI12nadJsZtIZHKOzYSBDoq0WoAw/IxzftldaF9EOM97KwaIxJHVUYlXQWuUo0m4VxbDDtkj01MM/DRCkuhYvZVNJH52TVk4aLhu1wahsDJ1ovIPO7LwApep+yPMvo/vTr96bXidheAGgMFv5tRhLzLUfSqsdGH5vdMaKk9m1wlnSnyfuAPWteefH/ELwgRKoWQaA3WRtjJGkJr9/rOB/cQvoi/sYq5SeP7x2hqiLRnN8sZr5V+lrMVe1VfOfS1OP2gLKUuCJQrvgNL6dKD+WUVhq5o4M60mkQ9+zeg5d9LKSjaqp/ayxUAkgOD1245jz7L77zQKbuIeMubs4fRuMIQXMjhdPINI+WEcynH6CfiYERXjyUaVizDpcSoPj/ms8gEaNaja9fbZ8ctOsDNvnh/VENfis/bCW6dG5lGtVQA/zTNQ8GeuT76WkavQHg+3Mp2xubqbjiI+9uKAnKUmrRHK5ISJneTC31cr+u0rDskFgFWaGhej5O+jFdpsZLjd7X8QSXeDsDhs1niv1QgMm55Hikjo8wVhUfUwQMrMGXheMFh2Ntb02PtUsA"
