apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key-secret
  namespace: cert-manager
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    api-token: "AgB4BijI5COg/D4Tn83kEHEACMc5gWuMXt7y3BIT8Z7FtLf20+3Xq5VgAn70ZCf00xSCDlueXGUF4mTijJjKugzHkAx8SOfKSIAssQUooSYwHOgfj//wK3T3+04laplNG5OMDFukr0kxgByizzjZzHjjtvMlaKAXNoEA4BBiN4vQY9xgJl/WMphsv2554O7MbAyQaVMzbvJUQjJp9St6tvumVtNjXLQxBMGj6dabxBLIMBm/8MPIC0ChnzIL9nxxWiL/5iVnhM+B7uzN6mcq62nvzUC165uNlBrqyNJ23EIeUg1asqQFeOPkJEi4RiuqsPrazbk4d962q0hkYUTN8iPC5Y3IULSHOnX+ZWNbLnRvdHKV7bKY/WqJtYAuEeTWG2d3zjDN3rWXDDhfHbKYY/TCqamrEz/LkiD15wz2GF90QoWFLeCZXRceH/HOFIa3/nYrnY8ZcaDZxkS4Eu09cYvGehVwjIZtKrj/bKqNAUuj99TsOaA4gpscnkXRuWpwdJRqWUU0qk1c0U0b9+vEXBaDvDJ5N5sJS8fZeYg+5ZxxjKbzIZdzfAP51L0Bj39bpzahr09RiVPkNZW7mJcJXnu+mkrxRULU4gokZEOnqN84/+fUsZAjVP+e5+rca+7k08SCHHnr4DA+qQDmwKLv5vDyvfjTY4mv6C9O6c495o+3sU90rl9gPEKGqJnaCB98FwmWT1cb2z3srnaTQvQOaw0WtTfr+yYRd4zl+WUpZTe1Lf464n9kfoD9"
