apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key-secret
  namespace: cert-manager
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    api-token: "AgCMRaTifMqEDGKz79NrDNgW/Y2hJoZsLsahsOonQQe6oPhIJu65+gKwHffDVCFA67ngUua+Jjv2XtCF5tnY+/2ZjujMVumYRZA3+hg4AcPADkXHkIp/HGAuECy/82CjopYUNs53USS50qYKNmlF4aarq1dpCMd4F48Zcr6wnJOiGRQgnajT1uQMV44Tk3B7xCHLSR+0PH2ACWWHOYVjanfvCX0RYs4v5NhK9QG2FxMhgIN5rrwoOnsokcN/NXlVV4n1L5zbQZ1yu3Iyuff30O739L3NxPrTTVgA8SYoATWnU8ZLb3Xntpqiz25UOg8HrZ6GtDijNrj2mtUdSAwrUHP1O7ITLub7JxVX91jZG2eyz9keC2H6qgs4EmYJa0JKQ82sj0sLLZhcjCZiJ1zY6HJIrks00/9hi+u/wP/GXTgK0sHtgs1NPdcBNSIuauESCU8kAYe2SLoRcits4+Ge9FIFACWGiEjCtQkl8B6MUoUsDKVs8hnmBeaLz1iKHDEU7uRd92LtoJSh8axvU5a8c3J3TujLbJEi9D6j5pQgDS4bvsH5AkKmcjWd7UOaVVVtF5GrQ3YAGA4VR68Q7pqyajBwm4cpQPeur3lJu53MRMEEDLNzsG+RvGHxNkHSz/Exhp7ndmnbuCnmSo/ztVUdqPJPFuxPBOUTGta2LC8zBF0uZSCimAfR/eDHEcPZHgRrpGHkZFzLyn6HEN09vqeleaw+3660vvtbUQ7WSWJKe2iDJi3svP+Os0oa"
