apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key-secret
  namespace: cert-manager
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    api-token: "AgCXTZCglEzPBt2dprayZhgDBFg2NdHwihmGNTcEyF1NN5g/Ypx7hywZ8MrWhQQuaVJLRK7MXnXcXHRM43xNS2SQ0QaIMi21eVB0HVz4DscVCGPcLRH9J9llZAlakjhieRFUYb2rea3cO+ih/CduU125mLC45pXKZNZLjrW5sP+PGHrb7ZmTvlOqSk5LD9SaaeYiPLrgHR5VcPaWcHBrFEnLaJuhvUa1BV1w7Ta09LSR8budsuwj2hkTQ960OjywfvlCA2VGtujKuajeBVuqJrlbRP2KU1rfbB/Wc35H/slWxhfk0YspFUcr0z0R3z/V/iUQe8d8n+Uiyr6fgNgxRP8A0wBFhG23XWC1A4D9QC2PXSLtSetQaEbIIsIa7fQhK/oCub57T5G0COy7DjeEG0e3Y97vAIRyYyPpz6x/cKTTay6OiKdze09AnOIWBDsbVqFCkKCtXEIRxEqfy+jPNo6ePTJSrt87pPV/KQsXkBOebgD05r0MzHNS0TPnfDqca7hYjBvcwW1deFAbCvRE02cOZ3JW4jV/CWmrN1k6mpvnNK7y+YUNcf2scl8S6AHSgS2c87n4HyZIZSSaeqXMXd8fadH8CNi1o8MDhQsqEk95qAKPKyNUZbZuhRf36U9sT8Kzo6REuivlfRsTw5DpfXT98W6OnhRzgI+Qxaamc61zilxA6+ia4e8FEHc4/jjlIJ//scRjXeSNaM9IoGygCN7Wkbx5u6a3r5tQ6XT1ek0jOJD2QyMgMsQB"
