apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key-secret
  namespace: cert-manager
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData: 
    api-token: AgDE1jLEbsfroBnjaIR3o+X7kYiutN2yF8OuZnFbZjGslEM6dx6Tb5OefKFJ7DWEIUKYXHiLZz5n2HTbwQU1xdYA28Orsz9md+SdpmHOfAaOW2hfdij70VPQg2rRJCADgt12uBBC91I6H9uh9JucZ9RFZjg3GtaDIcKrgglaE6D+fUsUqS3tXcgR3KmUiSA4ua/dag/Du+fd/PIljgRR4KHLFtov2AKky60XODclLV97nEaPmZayyU50lOSfrwdWRs+cLQ+QgBiwvwFN5DCVMYYM+JYQHOrw7JlbraTfE8M6Mogvq50MGtgwp/6W5gei3cxA2UBnkSTV3VWoDMQyUbGh729jZk/acsP6GN5wM5M02mgeU64vBVnb2z3x3Djh81kWINgac1eF8OVBRPxjGC7H9Hh22OPk8E92Pa22tOcmO5RdH/MuGES17+NorBunwup8z/DaMRFpjuGpLXRdgszEFHNIdbx4u88MmatIMYTVLoqahlfOB/aiu2rFrixgpv4PzJD1Egeo+jUSm682mr4Lj+LFGKzYTVO59odAahZJqnzzRVf3EasVQBiee4H4wPzSFxZVoHcLFJGSnTeI8JQDkA/KH6i28eKh4qOIHT2kkRlwbAn+g401Km6qtrk/9cmj7pbss84JERD3h/M9wgcXUQfQXi6pVuWAw0uBa+Xu7RnJsKkAZNDKTThNTh/pMO7JvKezpJtVGZeHyyZSE1TipnbXOzHL5lj33DaG9AUhiDkrVGFVIMGc
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: pbabbott@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-key-secret
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: pbabbott@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-key-secret
              key: api-token