apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key-secret
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData: 
    api-token: AgAb0W5kgQbK+PqSeWrTqQ9+vCcNb3BaK5p3UmI+Hlfp1PserdzlLcaWI8L3xordk0V/N5UsbHD1ZFA2rEEZqsSFpahqTC2NTcavbobPZwfmW16tNAnhNZhDLxRgT5DRwfBID74Yg+D1YEZ7FZrkyI3E8cOGLyq01sTrnZNkipi0sFB/4C5a4a/ugBSWfeywaV+AZ4E73f4cBZtz/z7rvA6Qq0pUa71lOrLbfSpFJ6JFD/U6xHr5Zte0m9VnBe16flIqWOmU3aUgkVIPSo9OKIeAmVZAW9IxEdL8pLiweQS4gDfj83rzN2hLLmOdm5UE94LRena9QIA0KeydBKU9Yjfa5lOb6T4wRCygOt/l2Ulwp5xN70yOp8PjuDiWkyxfHKTDN/zl7a41+/itzdkysnlZ4hAQaIoNdpSGj1CKp5Bymn/d1IcwOQwY3h/2xWLMmsNEpV1b0NHPo0nJcF3R2g2racOwh7oG+Is2lX5ADAAr1Mzed8Zb/Ii5hCPLCLDzgDgFzfx8Q+M9TtxBUOUTLjlQ81cAoQGON+u6C0cEAJxbguMQCAKh6GTsWUlwuNc2cDeN6TJillG92nAQI/fQyd0ng3OqJbjJk46NhhlYLOx36RUQ634zT122LTTnhMnI9QRqg+ekORC0JlaaRp+LPTttpNSRasmY8qTvsdZVYvvkZBFyxUeGBkz0+fOxem2U/02oO8V2BXdA0BW4kumPBhCsC9m2ATqN4O2up8IFOEsmMAQxPvf1ZGv1
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory

    # Email address used for ACME registration
    email: pbabbott@gmail.com

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging

    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: pbabbott@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx