apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./loki-helm-release.yaml
  - ./monitoring-helm-release.yaml
  - ./monitoring-helm-repo.yaml
  - ./monitoring-namespace.yaml
  - ./otc-helm-release.yaml
  - ./otc-helm-repo.yaml
