apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  releaseName: loki
  targetNamespace: monitoring
  chart:
    spec:
      chart: loki
      version: 6.29.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 30m
  values:
    loki: 
      storage:
        type: filesystem
