---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: monitoring
  releaseName: monitoring
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 70.2.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 12h
    # values:
    # grafana:
    #   enabled: true
    #   adminPassword: "admin"
    #   service:
    #     type: LoadBalancer
    # prometheus:
    #   prometheusSpec:
    #     retention: 10m
    # alertmanager:
    #   alertmanagerSpec:
    #     retention: 10m
    # kubeStateMetrics:
    #   enabled: true
    # nodeExporter:
    #   enabled: true
    # pushgateway:
    #   enabled: true
    # blackboxExporter:
    #   enabled: true
    # additionalScrapeConfigs:
    #   name: additional-scrape-configs
    #   key: prometheus-additional-scrape-configs.yaml