---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: monitoring
  releaseName: monitoring
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 70.2.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 12h
  values:
    alertmanager:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,192.168.0.0/16,172.20.0.0/12,10.244.0.0/16
        hosts:
          - alertmanager.local.abbottland.io
        tls:
          - secretName: alertmanager-tls
            hosts:
              - alertmanager.local.abbottland.io
    grafana:
      enabled: true
      defaultDashboardsEnabled: true
      defaultDashboardsTimezone: America/Chicago
      additionalDataSources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki.monitoring.svc:3100
          isDefault: false
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,192.168.0.0/16,172.20.0.0/12,10.244.0.0/16
        hosts:
          - grafana.local.abbottland.io
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.local.abbottland.io
    prometheus:
      prometheusSpec:
        additionalScrapeConfigs:
          # Re-label node-exporter to use the node name as the instance label
          - job_name: 'node-exporter-physical'
            relabel_configs:
              - source_labels: [__instance__]
                regex: 192\.168\.4\.157:9100
                action: replace
                target_label: host_type
                replacement: physical
            static_configs:
              - targets:
                - 192.168.4.192:9100
                labels:
                  nickname: chimaera
                  host_type: physical
              - targets:
                - 192.168.4.124:9100
                labels:
                  nickname: room_of_requirement
                  nodename: room_of_requirement
                  host_type: physical
              - targets:
                - 192.168.4.144:9100
                labels:
                  nickname: bananapi
                  host_type: physical
                

      enabled: true
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,192.168.0.0/16,172.20.0.0/12,10.244.0.0/16
        hosts:
          - prometheus.local.abbottland.io
        tls:
          - secretName: prometheus-tls
            hosts:
              - prometheus.local.abbottland.io
