apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-collector
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: monitoring
  chart:
    spec:
      chart: opentelemetry-collector
      version: 0.120.0
      sourceRef:
        kind: HelmRepository
        name: opentelemetry-helm
        namespace: flux-system
  values:
    image:
      repository: "otel/opentelemetry-collector-contrib"
    mode: daemonset
    presets:
      logsCollection:
        enabled: true
        includeCollectorLogs: true
    config:
      receivers:
        otlp:
          protocols:
            grpc: {}
            http: {}
        filelog:
          exclude:
            - /var/log/pods/monitoring_monitoring-opentelemetry-collector*_*/opentelemetry-collector/*.log 
            - /var/log/pods/monitoring_loki-*/*/*.log 
          include:
            - /var/log/pods/*/*/*.log
          include_file_name: false
          include_file_path: true
          operators:
            - id: container-parser
              max_log_size: 102400
              type: container
          retry_on_failure:
            enabled: true
          start_at: end
      exporters:
        otlphttp:
          endpoint: http://loki.monitoring.svc:3100/otlp
        prometheusremotewrite:
          endpoint: "http://prometheus.monitoring.svc:8889"
      service:
        pipelines:
          metrics:
            receivers: [otlp]
            exporters: [prometheusremotewrite]
          logs:
            exporters: [otlphttp]