apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-collector
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: monitoring
  chart:
    spec:
      chart: opentelemetry-collector
      version: 0.120.0
      sourceRef:
        kind: HelmRepository
        name: opentelemetry-helm
        namespace: flux-system
  values:
    image:
      repository: "otel/opentelemetry-collector-contrib"
    mode: deployment
    config:
      receivers:
        otlp:
          protocols:
            grpc:
            http:

      exporters:
        otlphttp:
          endpoint: http://loki.monitoring.svc:3100
        prometheusremotewrite:
          endpoint: "http://prometheus.monitoring.svc:8889"

      service:
        pipelines:
          # traces:
          #   receivers: [otlp]
          #   exporters: [otlphttp]
          metrics:
            receivers: [otlp]
            exporters: [prometheusremotewrite]
          logs:
            receivers: [otlp]
            exporters: [otlphttp]
