apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    version: "2.x"
    registry: ghcr.io/fluxcd
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
    - image-reflector-controller
    - image-automation-controller
  cluster:
    type: kubernetes
    multitenant: false
    multitenantWorkloadIdentity: false
    networkPolicy: true
    domain: cluster.local
  migrateResources: true
  wait: true
  sync:
    kind: GitRepository
    url: ssh://git@github.com/pbabbott/home-kubernetes
    ref: refs/heads/main
    path: clusters/non-prod-gen2
    pullSecret: flux-system
    interval: 1m
