apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - fluxinstance.yaml
  - ../../base/flux-gitops

patches:
  - target:
      kind: HelmRelease
      name: flux-operator-mcp
      namespace: flux-system
    patch: |-
      - op: replace
        path: /spec/values/httpRoute/hostnames/0
        value: flux-mcp.local.non-prod.abbottland.io
  - target:
      kind: HTTPRoute
      name: flux-web-http-to-https
      namespace: flux-system
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: flux.local.non-prod.abbottland.io
