---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cifs-secret
  namespace: longhorn-system
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/Homelab/items/cifs-secret"
