apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: fui-components
  namespace: flux-system
spec:
  image: harbor.local.abbottland.io/library/fui-components
  interval: 5m
  secretRef:
    name: regcred